import { readdir, readFile } from "fs/promises";
import { join, basename } from "path";

/**
 * COS API layer -- Phase 1 reads directly from the filesystem.
 * Phase 2+ will call the COS MCP server via subprocess or HTTP.
 */

const COS_ROOT = process.env.COS_ROOT || join(process.cwd(), "..");

// ---------------------------------------------------------------------------
// Status
// ---------------------------------------------------------------------------

export interface CosStatus {
  projectName: string;
  phase: string;
  cosVersion: string;
  rulesCount: number;
  hooksCount: number;
  skillsCount: number;
  packagesCount: number;
  activeSessions: number;
}

export async function getCosStatus(): Promise<CosStatus> {
  const [rulesCount, hooksCount, skillsCount, packagesCount, config] =
    await Promise.all([
      countFiles(join(COS_ROOT, "rules"), ".md"),
      countFiles(join(COS_ROOT, "hooks"), ".sh"),
      countSkills(join(COS_ROOT, "skills")),
      countDirectories(join(COS_ROOT, "packages")),
      readCosConfig(),
    ]);

  return {
    projectName: config.projectName,
    phase: config.phase,
    cosVersion: config.version,
    rulesCount,
    hooksCount,
    skillsCount,
    packagesCount,
    activeSessions: 0,
  };
}

// ---------------------------------------------------------------------------
// Rules
// ---------------------------------------------------------------------------

export interface CosRule {
  name: string;
  path: string;
}

export async function getRules(): Promise<CosRule[]> {
  const rulesDir = join(COS_ROOT, "rules");
  const rules: CosRule[] = [];

  try {
    const entries = await readdir(rulesDir);
    for (const entry of entries) {
      if (entry.endsWith(".md")) {
        const name = basename(entry, ".md");
        rules.push({ name, path: `rules/${entry}` });
      }
    }
  } catch {
    // Directory may not exist in test environments
  }

  return rules.sort((a, b) => a.name.localeCompare(b.name));
}

// ---------------------------------------------------------------------------
// Skills
// ---------------------------------------------------------------------------

export interface CosSkill {
  name: string;
  description: string;
  trigger?: string;
  autoGenerated: boolean;
}

export async function getSkills(): Promise<CosSkill[]> {
  const skillsDir = join(COS_ROOT, "skills");
  const skills: CosSkill[] = [];

  try {
    const entries = await readdir(skillsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const skillPath = join(skillsDir, entry.name, "SKILL.md");
      try {
        const content = await readFile(skillPath, "utf-8");
        const description = extractFirstParagraph(content);
        const trigger = entry.name;
        const autoGenerated = entry.name.startsWith("auto-") ||
          content.includes("auto-generated: true");

        skills.push({
          name: entry.name,
          description,
          trigger,
          autoGenerated,
        });
      } catch {
        // SKILL.md may not exist for all directories
        skills.push({
          name: entry.name,
          description: "No description available",
          autoGenerated: false,
        });
      }
    }
  } catch {
    // Directory may not exist
  }

  return skills.sort((a, b) => a.name.localeCompare(b.name));
}


// ---------------------------------------------------------------------------
// Primitive Surface Coverage
// ---------------------------------------------------------------------------

export interface PrimitiveSurfaceCoverageSummary {
  totalPrimitives: number;
  gaps: number;
  unclassifiedGaps: number;
  surfacesByKind: Record<string, number>;
  surfaceProjectedOrWired: Record<string, number>;
  consumesReport: boolean;
  mode: "observe-only";
}

export async function getPrimitiveSurfaceCoverageSummary(): Promise<PrimitiveSurfaceCoverageSummary> {
  const reportPath = join(COS_ROOT, "docs", "reports", "primitive-harness-coverage-latest.json");

  try {
    const content = await readFile(reportPath, "utf-8");
    const report = JSON.parse(content);
    const summary = report.summary || {};

    return {
      totalPrimitives: Number(summary.total_primitives || 0),
      gaps: Number(summary.gaps || 0),
      unclassifiedGaps: Number(summary.unclassified_gaps || 0),
      surfacesByKind: summary.surfaces_by_kind || {},
      surfaceProjectedOrWired: summary.surface_projected_or_wired || summary.harness_projected_or_wired || {},
      consumesReport: true,
      mode: "observe-only",
    };
  } catch {
    return {
      totalPrimitives: 0,
      gaps: 0,
      unclassifiedGaps: 0,
      surfacesByKind: {},
      surfaceProjectedOrWired: {},
      consumesReport: false,
      mode: "observe-only",
    };
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function countFiles(dir: string, ext: string): Promise<number> {
  try {
    const entries = await readdir(dir);
    return entries.filter((e) => e.endsWith(ext)).length;
  } catch {
    return 0;
  }
}

async function countSkills(dir: string): Promise<number> {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries.filter((e) => e.isDirectory()).length;
  } catch {
    return 0;
  }
}

async function countDirectories(dir: string): Promise<number> {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries.filter((e) => e.isDirectory()).length;
  } catch {
    return 0;
  }
}

interface CosConfig {
  projectName: string;
  phase: string;
  version: string;
}

async function readCosConfig(): Promise<CosConfig> {
  try {
    const content = await readFile(
      join(COS_ROOT, "cognitive-os.yaml"),
      "utf-8"
    );
    // Simple YAML extraction without a parser dependency
    const phase = extractYamlValue(content, "phase") || "reconstruction";
    const name = extractYamlValue(content, "name") || "luum-agent-os";
    const version = extractYamlValue(content, "version") || "0.0.0";
    return { projectName: name, phase, version };
  } catch {
    return {
      projectName: "unknown",
      phase: "unknown",
      version: "0.0.0",
    };
  }
}

function extractYamlValue(content: string, key: string): string | null {
  const regex = new RegExp(`^\\s*${key}:\\s*(.+)$`, "m");
  const match = content.match(regex);
  return match ? match[1].trim().replace(/^["']|["']$/g, "") : null;
}

function extractFirstParagraph(markdown: string): string {
  const lines = markdown.split("\n");
  const paragraphLines: string[] = [];
  let started = false;

  for (const line of lines) {
    const trimmed = line.trim();
    // Skip frontmatter and headings
    if (trimmed.startsWith("---") || trimmed.startsWith("#")) {
      if (started) break;
      continue;
    }
    if (trimmed === "") {
      if (started) break;
      continue;
    }
    started = true;
    paragraphLines.push(trimmed);
  }

  return paragraphLines.join(" ").slice(0, 200) || "No description";
}
