from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[3]
OS_ONLY_PRIMITIVE_PROOF_BASELINE = [
    'hooks/aci-observation-capture.sh',
    'hooks/adoption-freeze-gate.sh',
    'hooks/adr-section-validator.sh',
    'hooks/adversarial-review-gate.sh',
    'hooks/agent-quota-redirect.sh',
    'hooks/agnix-lint.sh',
    'hooks/aspirational-audit-weekly.sh',
    'hooks/attribution-completeness-validator.sh',
    'hooks/auto-skill-generator.sh',
    'hooks/clean-room-ast-similarity-gate.sh',
    'hooks/codebase-itinerary-capture.sh',
    'hooks/cognitive-os-health.sh',
    'hooks/completeness-check.sh',
    'hooks/conversation-capture.sh',
    'hooks/cos-executor-daemon-launcher.sh',
    'hooks/cos-executor-heartbeat.sh',
    'hooks/cosd-intent-submit.sh',
    'hooks/dependency-license-classifier.sh',
    'hooks/dequeue-notify.sh',
    'hooks/dispatch-gate.sh',
    'hooks/docker-drift-detector.sh',
    'hooks/ecosystem-check.sh',
    'hooks/engram-auto-import.sh',
    'hooks/engram-auto-sync.sh',
    'hooks/external-cache-content-leak.sh',
    'hooks/external-pattern-cleanroom-gate.sh',
    'hooks/history-rewrite-documented.sh',
    'hooks/hook-header-validator.sh',
    'hooks/idle-service-cleanup.sh',
    'hooks/kpi-trigger.sh',
    'hooks/legal-review-required-on-runtime-import.sh',
    'hooks/lethal-trifecta-gate.sh',
    'hooks/lib-symlink-divergence-detector.sh',
    'hooks/memu-sync.sh',
    'hooks/metrics-calibrator-trigger.sh',
    'hooks/metrics-rotation.sh',
    'hooks/mlflow-sync.sh',
    'hooks/native-agent-heartbeat.sh',
    'hooks/package-sync.sh',
    'hooks/pattern-check.sh',
    'hooks/post-agent-snapshot-restore.sh',
    'hooks/pre-cleanup-snapshot.sh',
    'hooks/promotion-proposer-weekly.sh',
    'hooks/pyrefly-typecheck-advisory.sh',
    'hooks/rate-limit-detector.sh',
    'hooks/reaper-daemon-launcher.sh',
    'hooks/reaper-heartbeat.sh',
    'hooks/recap-sync.sh',
    'hooks/registration-check.sh',
    'hooks/research-to-runtime-firewall.sh',
    'hooks/review-spawner.sh',
    'hooks/rule-frontmatter-validator.sh',
    'hooks/rule-md-routing-validator.sh',
    'hooks/self-install.sh',
    'hooks/self-knowledge-refresh.sh',
    'hooks/session-changelog.sh',
    'hooks/session-end-reap.sh',
    'hooks/session-hygiene.sh',
    'hooks/session-knowledge-extractor.sh',
    'hooks/session-resume.sh',
    'hooks/session-start-stack-recommend.sh',
    'hooks/session-state-save.sh',
    'hooks/session-watchdog-launcher.sh',
    'hooks/singularity-check.sh',
    'hooks/skill-drift-detector.sh',
    'hooks/skill-failure-monitor.sh',
    'hooks/skill-feedback-tracker.sh',
    'hooks/skill-invocation-logger.sh',
    'hooks/skill-md-routing-validator.sh',
    'hooks/skill-synthesis-scanner.sh',
    'hooks/skill-tracker.sh',
    'hooks/skill-usage-tracker.sh',
    'hooks/spdx-header-required.sh',
    'hooks/stash-budget-warn.sh',
    'hooks/state-heartbeat.sh',
    'hooks/sync-to-repo.sh',
    'hooks/task-bridge-notify.sh',
    'hooks/telemetry-budget-violator-detect.sh',
    'hooks/tool-discovery-trigger.sh',
    'hooks/tool-sequence-capture.sh',
    'hooks/usage-health-check.sh',
    'hooks/validation-lock-cleanup.sh',
    'hooks/validator-soak-weekly.sh',
    'hooks/work-queue-sync.sh',
    'rules/ROADMAP.md',
    'rules/capability-protection.md',
    'rules/clean-room-detection-limits.md',
    'rules/lane-taxonomy.md',
    'rules/pre-dev-readiness-gate.md',
    'rules/reinvention-prevention.md',
    'scripts/adr100_live_headroom_check.py',
    'scripts/adr_reserve.py',
    'scripts/agent-orchestration-benchmark.py',
    'scripts/agent-orchestration-boundary-audit.py',
    'scripts/agentic-tool-license-matrix.sh',
    'scripts/agentic_mastery_summary.py',
    'scripts/agentic_tool_license_matrix.py',
    'scripts/ai-provider-identity-guard',
    'scripts/align_skill_frontmatter.py',
    'scripts/apply-efficiency-profile.sh',
    'scripts/aspirational_audit.py',
    'scripts/audit-consumer-dependence.sh',
    'scripts/audit_adrs.py',
    'scripts/audit_engram_topic_keys.py',
    'scripts/auto-tune-routing',
    'scripts/auto-update-projects.sh',
    'scripts/auto_tune_routing.py',
    'scripts/backfill_session_decisions.py',
    'scripts/benchmark-hooks.sh',
    'scripts/benchmark-providers',
    'scripts/benchmark_providers.py',
    'scripts/chaos/snapshot-concurrent-race.sh',
    'scripts/chaos/snapshot-crash-rollback.sh',
    'scripts/chaos/snapshot-vanishing-untracked.sh',
    'scripts/check-upstream-changes.sh',
    'scripts/check_entrypoint_adr_links.py',
    'scripts/check_lazy_catalog_health.py',
    'scripts/ci-setup.sh',
    'scripts/ci-smoke-linux.sh',
    'scripts/claim_enforcer.py',
    'scripts/claim_proof_audit.py',
    'scripts/cleanup-snapshots.sh',
    'scripts/commit_provenance.py',
    'scripts/component-lint.sh',
    'scripts/cos-active-primitive-index',
    'scripts/cos-adoption-profile',
    'scripts/cos-adoption-unfreeze',
    'scripts/cos-adr-close',
    'scripts/cos-adr-partial-audit',
    'scripts/cos-adr-partial-ledger',
    'scripts/cos-adr-resolve',
    'scripts/cos-agent-message',
    'scripts/cos-agent-spawn-benchmark',
    'scripts/cos-agent-worktree-prepare',
    'scripts/cos-auth-probe',
    'scripts/cos-bootstrap.sh',
    'scripts/cos-boring-reliability',
    'scripts/cos-branch-lease',
    'scripts/cos-branch-lock',
    'scripts/cos-branch-release',
    'scripts/cos-branch-task-check',
    'scripts/cos-capability-matrix',
    'scripts/cos-ci-local.sh',
    'scripts/cos-claim-signature-audit',
    'scripts/cos-cleanup.sh',
    'scripts/cos-closure-discipline-audit',
    'scripts/cos-cloud-worker-bootstrap.sh',
    'scripts/cos-context-budget-report',
    'scripts/cos-control-plane-audit',
    'scripts/cos-core-skills-check.sh',
    'scripts/cos-counsel-outreach-draft',
    'scripts/cos-counsel-packet',
    'scripts/cos-credential-safe-run',
    'scripts/cos-cross-stack-adoption-truth',
    'scripts/cos-cross-stack-license-audit',
    'scripts/cos-cross-stack-secret-audit',
    'scripts/cos-default-visible-reducer',
    'scripts/cos-deferred-tool-plan',
    'scripts/cos-demotion-proposer',
    'scripts/cos-dependency-adoption-gate',
    'scripts/cos-deps-coverage-audit',
    'scripts/cos-deps-install.sh',
    'scripts/cos-deps-maintain',
    'scripts/cos-deps-profile-ratchet',
    'scripts/cos-deps-triage',
    'scripts/cos-dispatch-smoke',
    'scripts/cos-doc-path-audit',
    'scripts/cos-doctor-memory-lifecycle.sh',
    'scripts/cos-doctor-tools.sh',
    'scripts/cos-documentation-truth-audit',
    'scripts/cos-engram-cloud-docker-smoke',
    'scripts/cos-engram-command-audit',
    'scripts/cos-engram-wave2-schema-migrate',
    'scripts/cos-external-source-fetch',
    'scripts/cos-false-positive-ledger',
    'scripts/cos-falsification-benchmark',
    'scripts/cos-feature-tool-scan',
    'scripts/cos-feature-vs-tool-benchmark',
    'scripts/cos-filter-repo-wrap.sh',
    'scripts/cos-fleet-confidence-export',
    'scripts/cos-flow-register.sh',
    'scripts/cos-friction-report',
    'scripts/cos-generate-notices.py',
    'scripts/cos-ghost-skills.sh',
    'scripts/cos-headless-service-drill',
    'scripts/cos-history-rewrite-audit',
    'scripts/cos-history-sanitization',
    'scripts/cos-history-sanitization-smoke.sh',
    'scripts/cos-imported-pattern-closure-audit',
    'scripts/cos-init-global.sh',
    'scripts/cos-install-projection-audit',
    'scripts/cos-install-scope-dev-smoke',
    'scripts/cos-instance-init',
    'scripts/cos-language-dependence-audit',
    'scripts/cos-legal-approve',
    'scripts/cos-maintainer-agent',
    'scripts/cos-memory-benchmark',
    'scripts/cos-memory-benchmark-compare',
    'scripts/cos-operational-status',
    'scripts/cos-performance-ledger',
    'scripts/cos-policy-eval',
    'scripts/cos-postmortem-regression-audit',
    'scripts/cos-pr-review.sh',
    'scripts/cos-pre-public-risk-audit',
    'scripts/cos-preamble-budget',
    'scripts/cos-primitive-fitness-ledger',
    'scripts/cos-private-content-audit',
    'scripts/cos-product-answer',
    'scripts/cos-product-answer-refresh',
    'scripts/cos-profile-explain',
    'scripts/cos-project-registry-prune.sh',
    'scripts/cos-promote-from-telemetry',
    'scripts/cos-promotion-proposer',
    'scripts/cos-public-claim-gate',
    'scripts/cos-pyrefly-pilot',
    'scripts/cos-pytest-serial-repair',
    'scripts/cos-python-stdin-antipattern-audit',
    'scripts/cos-queue-drain',
    'scripts/cos-recovery-drill',
    'scripts/cos-registry.sh',
    'scripts/cos-release-external-readiness',
    'scripts/cos-release-freeze',
    'scripts/cos-reward-signal-audit',
    'scripts/cos-rollback',
    'scripts/cos-routing-benchmark',
    'scripts/cos-run-trace',
    'scripts/cos-runtime-hook-reality',
    'scripts/cos-rust-transpiler-eval',
    'scripts/cos-sandbox-run',
    'scripts/cos-scope-projection-audit',
    'scripts/cos-script-exposure-audit',
    'scripts/cos-self-programming-pattern-audit',
    'scripts/cos-session-coordination',
    'scripts/cos-session-spawn.sh',
    'scripts/cos-session-start-budget',
    'scripts/cos-sessions.sh',
    'scripts/cos-silent-failure-audit',
    'scripts/cos-skill-description-enrich',
    'scripts/cos-skill-performance-ledger',
    'scripts/cos-startup-recover.sh',
    'scripts/cos-task-submit',
    'scripts/cos-telemetry-aggregate',
    'scripts/cos-test-efficiency-plan',
    'scripts/cos-test-repair-loop',
    'scripts/cos-tool-adoption-audit',
    'scripts/cos-tool-discovery-preuse',
    'scripts/cos-tool-inventory',
    'scripts/cos-tool-radar-render',
    'scripts/cos-tool-research-check',
    'scripts/cos-update.sh',
    'scripts/cos-uspto-patent-search',
    'scripts/cos-uspto-trademark-search',
    'scripts/cos-validation-break.sh',
    'scripts/cos-validation-status.sh',
    'scripts/cos-vs-ai-slop-two-repo-smoke',
    'scripts/cos-weekly-config-audit.sh',
    'scripts/cos-weekly-primitive-gap.sh',
    'scripts/cos-weekly-public-metrics.sh',
    'scripts/cos-wip-safety-score',
    'scripts/cos-worker-run-once',
    'scripts/cos-worktree-audit',
    'scripts/cos-worktree-sweeper.sh',
    'scripts/cos_auth_probe.py',
    'scripts/cos_branch_lease.py',
    'scripts/cos_build_self_knowledge.py',
    'scripts/cos_chaos_template.py',
    'scripts/cos_classify_coverage.py',
    'scripts/cos_clean_room_ast_similarity.py',
    'scripts/cos_closure_discipline_audit.py',
    'scripts/cos_codex_guard.py',
    'scripts/cos_consumer_fleet_audit.py',
    'scripts/cos_credential_safe_run.py',
    'scripts/cos_daemon.py',
    'scripts/cos_demotion_proposer.py',
    'scripts/cos_deps_install.py',
    'scripts/cos_doc_path_audit.py',
    'scripts/cos_engram_command_audit.py',
    'scripts/cos_evolve_tick.py',
    'scripts/cos_executor.py',
    'scripts/cos_falsification_benchmark.py',
    'scripts/cos_flow_register.py',
    'scripts/cos_friction_report.py',
    'scripts/cos_governed_runner.py',
    'scripts/cos_headless_safe_mode.py',
    'scripts/cos_install_projection_audit.py',
    'scripts/cos_install_scope_dev_smoke.py',
    'scripts/cos_instance_init.py',
    'scripts/cos_lib_symlink_invariant_audit.py',
    'scripts/cos_operational_status.py',
    'scripts/cos_profile_explain.py',
    'scripts/cos_promotion_proposer.py',
    'scripts/cos_repair.py',
    'scripts/cos_rust_transpiler_eval.py',
    'scripts/cos_service_control_plane.py',
    'scripts/cos_sprint.py',
    'scripts/cos_test_artifact_status.py',
    'scripts/cos_validate.py',
    'scripts/cos_verbatim_copy_detector.py',
    'scripts/cos_vs_ai_slop_two_repo_smoke.py',
    'scripts/cos_watch.py',
    'scripts/cos_work_queue.py',
    'scripts/cosd',
    'scripts/create-release.sh',
    'scripts/dangerous_env_flag_detector.py',
    'scripts/demo-consumer-sdd-lane.sh',
    'scripts/demo-first-run-onboarding.sh',
    'scripts/demo-governance.sh',
    'scripts/demo-portability-proof.sh',
    'scripts/dependency-lane.sh',
    'scripts/deps-update.sh',
    'scripts/detect_runner_capacity.py',
    'scripts/docs_duplicate_audit.py',
    'scripts/dogfood_score.py',
    'scripts/generate-project-settings.sh',
    'scripts/generate_adr_index.py',
    'scripts/generate_adversarial_scenario.py',
    'scripts/generate_harness_projection_registry.py',
    'scripts/git-coop.sh',
    'scripts/hook_quality_audit.py',
    'scripts/install-cos.sh',
    'scripts/install-git-filter-repo.sh',
    'scripts/install-git-hooks.sh',
    'scripts/install-goreleaser.sh',
    'scripts/install-launchd-jobs.sh',
    'scripts/install-pre-commit.sh',
    'scripts/install-timing-test.sh',
    'scripts/lint-shell.sh',
    'scripts/manifest-check.sh',
    'scripts/mcp_tofu_audit.py',
    'scripts/measure_expansion.py',
    'scripts/measure_harness_profiles.py',
    'scripts/merge-settings.sh',
    'scripts/metrics_tamper_audit.py',
    'scripts/migrate-to-cognitive-os.sh',
    'scripts/migrate_event_log_to_v2.py',
    'scripts/migrate_skill_archive_to_store.py',
    'scripts/migrate_skill_descriptions_use_when.py',
    'scripts/network_egress_guard.py',
    'scripts/network_sandbox_run.py',
    'scripts/plan-lock.sh',
    'scripts/postinstall.js',
    'scripts/prelaunch-apply-rewrite',
    'scripts/prelaunch-history-audit',
    'scripts/prelaunch-message-audit',
    'scripts/prelaunch-rewrite-plan',
    'scripts/primitive-behavior-audit.py',
    'scripts/primitive-coherence-audit.py',
    'scripts/primitive-scope-balance-audit',
    'scripts/primitive-scope-dependency-audit',
    'scripts/primitive-scope-false-both-audit',
    'scripts/primitive-scope-generic-os-only-audit',
    'scripts/primitive-scope-health',
    'scripts/primitive-scope-plane-audit',
    'scripts/primitive-scope-proof-audit',
    'scripts/primitive-scope-random-audit',
    'scripts/primitive_backend_benchmark.py',
    'scripts/primitive_coverage.py',
    'scripts/primitive_duplication_audit.py',
    'scripts/primitive_family_readiness_ledger.py',
    'scripts/primitive_gap_snapshot.py',
    'scripts/primitive_lifecycle.py',
    'scripts/primitive_parse_inventory.py',
    'scripts/primitive_readiness_ledger.py',
    'scripts/primitive_row_audit.py',
    'scripts/primitive_scope_classifier.py',
    'scripts/primitive_scope_dependency_audit.py',
    'scripts/primitive_scope_health.py',
    'scripts/primitive_scope_random_audit.py',
    'scripts/primitive_scope_unknown_triage.py',
    'scripts/primitive_structure_standardizer.py',
    'scripts/primitive_surface_reduce.py',
    'scripts/primitive_usage_map.py',
    'scripts/private_content_audit.py',
    'scripts/provider_spoof_audit.py',
    'scripts/reduction_backlog.py',
    'scripts/regen_catalog_bullets.py',
    'scripts/register-mcps.sh',
    'scripts/render_adoption_tiers.py',
    'scripts/reserve_adr_slot.py',
    'scripts/review_pending_sweeper.py',
    'scripts/run-adversarial-generalization.sh',
    'scripts/run-runtime-benchmark.sh',
    'scripts/run_skill_efficacy_smoke.py',
    'scripts/runtime_benchmark_report.py',
    'scripts/scope_tag_backfill.py',
    'scripts/security_red_team.py',
    'scripts/self_programming_pattern_audit.py',
    'scripts/semantic-lookup.mjs',
    'scripts/session-leak-diagnostic.sh',
    'scripts/set-security-profile.sh',
    'scripts/setup-git-hooks.sh',
    'scripts/skill-router-benchmark.py',
    'scripts/skill-router-retrieval-audit.py',
    'scripts/skill_efficacy_report.py',
    'scripts/smoke-agent-quota-redirect.sh',
    'scripts/so_session_watchdog.py',
    'scripts/so_vs_vanilla_benchmark.py',
    'scripts/subagent_launch_preflight.py',
    'scripts/test-agent-teams-hooks.sh',
    'scripts/test-cognitive-os.sh',
    'scripts/test-mcp-server.sh',
    'scripts/test_run_inventory.py',
    'scripts/test_skip_registry.py',
    'scripts/uninstall.sh',
    'scripts/update_readme_badges.py',
    'scripts/upgrade.sh',
    'scripts/validate_substrate_consumers.py',
    'scripts/validate_tier_filter.py',
    'scripts/version.sh',
    'scripts/weekly-aspirational-audit.sh',
    'scripts/write_context_marker.py',
    'skills/__contracts__/SKILL.md',
    'skills/__contracts__/canonical-event-emitter/SKILL.md',
    'skills/adr-tombstone/SKILL.md',
    'skills/architecture-map-answer/SKILL.md',
    'skills/audit-integrity/SKILL.md',
    'skills/browser-task/SKILL.md',
    'skills/bump-version/SKILL.md',
    'skills/cognitive-os-init/SKILL.md',
    'skills/cognitive-os-status/SKILL.md',
    'skills/cognitive-os-test/SKILL.md',
    'skills/component-reality-check/SKILL.md',
    'skills/os-session-wrapup/SKILL.md',
    'skills/coordination-status/SKILL.md',
    'skills/cos-install-operations/SKILL.md',
    'skills/cos-maintainer-operations/SKILL.md',
    'skills/deps-update/SKILL.md',
    'skills/docs-execution-audit/SKILL.md',
    'skills/dogfood-score/SKILL.md',
    'skills/experimental/SKILL.md',
    'skills/experimental/auto-bash-agent-bash-9c6b89/SKILL.md',
    'skills/generate-changelog/SKILL.md',
    'skills/hook-timing/SKILL.md',
    'skills/memory-scan/SKILL.md',
    'skills/primitive-surface-reduction/SKILL.md',
    'skills/primitive-usage-map/SKILL.md',
    'skills/product-answer/SKILL.md',
    'skills/push-release/SKILL.md',
    'skills/pyrefly-typecheck/SKILL.md',
    'skills/radar-update/SKILL.md',
    'skills/release-os/SKILL.md',
    'skills/repair-skill/SKILL.md',
    'skills/so-vs-vanilla/SKILL.md',
    'skills/synthesize-skill/SKILL.md',
    'skills/tag-release/SKILL.md',
    'skills/test-contract-repair/SKILL.md',
    'skills/validate-release/SKILL.md',
    'skills/vuln-remediation-flow/SKILL.md',
    'templates/agent-mandatory-rules.md',
    'templates/agent-preamble.md',
    'templates/counsel-outreach/clean-room-permission.md',
    'templates/counsel-outreach/license-clarification.md',
    'templates/counsel-outreach/review-request.md',
    'templates/edit-conflict-response.md',
    'templates/hook-template.sh',
    'templates/project-gotchas.md',
    'templates/rebranding-checklist.md',
    'templates/rule-template.md',
    'templates/skill-template.md',
]


def _load_health_module():
    module_path = ROOT / "scripts" / "primitive_scope_health.py"
    spec = importlib.util.spec_from_file_location("primitive_scope_health_os_only_family", module_path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_os_only_scope_family_has_maintainer_metadata_and_non_user_plane() -> None:
    health = _load_health_module()
    rows = {row.path: row for row in health.build_rows(ROOT)}

    for rel in OS_ONLY_PRIMITIVE_PROOF_BASELINE:
        path = ROOT / rel
        assert path.exists(), rel
        row = rows[rel]
        assert row.scope == "os-only", rel
        assert row.consumer_surface == "maintainer-only", rel
        assert row.plane in {"control-plane", "factory-plane", "runtime-plane"}, rel
        assert row.plane != "user-plane", rel


def test_os_only_scope_family_is_registered_as_behavior_evidence() -> None:
    manifest = ROOT / "manifests" / "primitive-behavior-evidence.yaml"
    data = yaml.safe_load(manifest.read_text(encoding="utf-8"))
    evidence = {item["primitive"]: item for item in data["evidence"]}

    for rel in OS_ONLY_PRIMITIVE_PROOF_BASELINE:
        tests = evidence[rel]["tests"]
        assert "tests/red_team/portability/test_os_only_scope_family.py" in tests, rel


def test_os_only_scope_none_budget_is_zero_after_family_proof() -> None:
    out = ROOT / ".cognitive-os" / "reports" / "test-os-only-scope-family-health.json"
    subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "primitive_scope_health.py"),
            "--project-dir",
            str(ROOT),
            "--mode",
            "proof",
            "--strict",
            "--json-out",
            str(out),
        ],
        check=True,
    )
    payload = json.loads(out.read_text(encoding="utf-8"))
    assert payload["summary"]["findings"] == 0
    assert payload["summary"]["by_proof_level"].get("none", 0) == 0
