#!/usr/bin/env bash
# PreToolUse hook on Agent — injects phase context from cognitive-os.yaml into agent prompts.
# Universal hook: reads project type and phase from config, does NOT hardcode any
# project-specific architecture standards or constitutional gates.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
COGNITIVE_OS_DIR="$PROJECT_DIR/.cognitive-os"
COGNITIVE_OS_YAML="$COGNITIVE_OS_DIR/cognitive-os.yaml"

# Read input from stdin
INPUT=$(cat)

# Only process Agent tool calls
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null)
if [[ "$TOOL_NAME" != "Agent" && "$TOOL_NAME" != "task" && "$TOOL_NAME" != "delegate" ]]; then
  exit 0
fi

# --- Phase Context ---
PHASE="reconstruction"
if [[ -f "$COGNITIVE_OS_YAML" ]]; then
  PHASE=$(grep -E '^\s+phase:' "$COGNITIVE_OS_YAML" | head -1 | sed 's/.*phase:\s*//' | sed 's/\s*#.*//' | tr -d '[:space:]' || echo "reconstruction")
fi

# Build phase-specific rules (universal, not framework-specific)
case "$PHASE" in
  reconstruction)
    RULES="- Rewrite > patch. Do NOT preserve broken patterns.
- Follow project architecture standards strictly.
- Don't document as \"future work\" — DO IT NOW.
- Break backwards compatibility if needed.
- Architecture violations are BLOCKERS, not warnings.
- If something doesn't compile after rewriting, FIX IT in this session."
    ;;
  stabilization)
    RULES="- Follow project architecture standards strictly.
- Rewrite non-compliant code (don't just patch).
- Maintain backwards compatibility where possible.
- Architecture violations should be fixed or tracked as tasks."
    ;;
  production)
    RULES="- Do NOT break existing functionality.
- Use feature flags for all changes.
- Document risky changes as proposals, not implementations.
- Maintain backwards compatibility.
- Architecture violations are warnings — log but don't block."
    ;;
  maintenance)
    RULES="- Bug fixes and security patches ONLY.
- Minimal changes, maximum stability.
- Document improvements as future work.
- Do NOT refactor or restructure."
    ;;
  *)
    RULES="- Unknown phase ($PHASE). Default to conservative behavior."
    ;;
esac

# --- Project Type ---
PROJECT_TYPE="webapp"
PROJECT_NAME="my-project"
if [[ -f "$COGNITIVE_OS_YAML" ]]; then
  PROJECT_TYPE=$(grep -E '^\s+type:' "$COGNITIVE_OS_YAML" | head -1 | sed 's/.*type:\s*//' | sed 's/\s*#.*//' | tr -d '[:space:]' || echo "webapp")
  PROJECT_NAME=$(grep -E '^\s+name:' "$COGNITIVE_OS_YAML" | head -1 | sed 's/.*name:\s*//' | sed 's/\s*#.*//' | tr -d '[:space:]' || echo "my-project")
fi

# --- Squad Assignment (if applicable) ---
SQUAD_INFO=""
SQUADS_DIR="$COGNITIVE_OS_DIR/squads"
if [[ -d "$SQUADS_DIR" ]]; then
  ACTIVE_SQUAD=$(grep -E '^\s+active_squad:' "$COGNITIVE_OS_YAML" 2>/dev/null | head -1 | sed 's/.*active_squad:\s*//' | sed 's/\s*#.*//' | tr -d '[:space:]' || echo "")
  if [[ -n "$ACTIVE_SQUAD" && -f "$SQUADS_DIR/$ACTIVE_SQUAD.md" ]]; then
    SQUAD_INFO="ACTIVE SQUAD: $ACTIVE_SQUAD"
  fi
fi

# --- Load project-specific context from .claude/ if it exists ---
# Architecture standards and constitutional gates are project-specific
# and should be defined in {project}/.claude/rules/ not here.
PROJECT_CONTEXT=""
PROJECT_RULES_DIR="$PROJECT_DIR/.claude/rules"
if [[ -d "$PROJECT_RULES_DIR" ]]; then
  # Check for architecture rules
  if [[ -f "$PROJECT_RULES_DIR/architecture.md" ]]; then
    PROJECT_CONTEXT="${PROJECT_CONTEXT}\nSee .claude/rules/architecture.md for project architecture standards."
  fi
  # Check for constitutional gates
  if [[ -f "$PROJECT_RULES_DIR/constitutional-gates.md" ]]; then
    PROJECT_CONTEXT="${PROJECT_CONTEXT}\nSee .claude/rules/constitutional-gates.md for project constitutional gates."
  fi
fi

# --- Keyword-based gotcha injection ---
# Extract agent prompt to scan for keywords
AGENT_PROMPT=$(echo "$INPUT" | jq -r '.tool_input.prompt // empty' 2>/dev/null)
GOTCHAS=""

if [[ -n "$AGENT_PROMPT" ]]; then
  # lib/ symlink trap
  if echo "$AGENT_PROMPT" | grep -qiE 'lib/|packages/.*lib|duplicate.*lib|dedup'; then
    GOTCHAS="${GOTCHAS}
WARNING: lib/*.py are SYMLINKS to packages/*/lib/*.py — NOT duplicates. Verify with: ls -la lib/<file>.py. NEVER replace files in packages/*/lib/."
  fi

  # settings.json trap
  if echo "$AGENT_PROMPT" | grep -qiE 'settings\.json|wire.*hook|add.*hook.*settings'; then
    GOTCHAS="${GOTCHAS}
WARNING: .claude/settings.json is GENERATED by scripts/apply-efficiency-profile.sh. Do NOT edit it directly. Update the script, then run: bash scripts/apply-efficiency-profile.sh standard"
  fi

  # Hook creation trap
  if echo "$AGENT_PROMPT" | grep -qiE 'new hook|create hook|hooks/.*\.sh'; then
    GOTCHAS="${GOTCHAS}
WARNING: New hooks MUST be registered in scripts/apply-efficiency-profile.sh under the appropriate profile (lean/standard/full) or they will NEVER fire."
  fi

  # Workflow trap
  if echo "$AGENT_PROMPT" | grep -qiE 'workflow|pipeline.*yaml|\.cognitive-os/workflows'; then
    GOTCHAS="${GOTCHAS}
WARNING: Workflow YAMLs in .cognitive-os/workflows/ must follow the schema in docs/adw-patterns.md. Steps have type: agent|script|gate."
  fi

  # Plans directory trap
  if echo "$AGENT_PROMPT" | grep -qiE 'plans/|plan.*directory'; then
    GOTCHAS="${GOTCHAS}
WARNING: plans/ at root has structure but no content. Active plans are in .cognitive-os/plans/. Both exist intentionally."
  fi
fi

# --- Engram discovery injection (best-effort, 3s timeout) ---
ENGRAM_WARNINGS=""
if [[ -n "$AGENT_PROMPT" ]] && command -v python3 >/dev/null 2>&1; then
  # Extract key nouns from the prompt for Engram search
  SEARCH_TERMS=$(echo "$AGENT_PROMPT" | grep -oE '\b(lib|hook|settings|workflow|pipeline|packages|symlink|duplicate|profile|efficiency)\b' 2>/dev/null | sort -u | head -3 | tr '\n' ' ' || true)
  if [[ -n "$SEARCH_TERMS" ]]; then
    ENGRAM_WARNINGS=$(timeout 3 python3 -c "
import sys, json, subprocess
try:
    # Search engram for discovery-type memories matching keywords
    for term in '${SEARCH_TERMS}'.split():
        result = subprocess.run(
            ['python3', '-c', '''
import sys
sys.path.insert(0, \"$PROJECT_DIR\")
try:
    from lib.engram_client import search_observations
    results = search_observations(term.strip(), limit=2)
    for r in results:
        t = r.get(\"type\", \"\")
        if t in (\"discovery\", \"bugfix\", \"feedback\"):
            title = r.get(\"title\", \"\")[:80]
            print(f\"ENGRAM [{t}]: {title}\")
except Exception:
    pass
'''.replace('term.strip()', repr(term.strip()))],
            capture_output=True, text=True, timeout=3
        )
        if result.returncode == 0 and result.stdout.strip():
            print(result.stdout.strip())
except Exception:
    pass
" 2>/dev/null || true)
  fi
fi

# --- Guard: skip preamble injection if already present in prompt ---
# This prevents double-injection if multiple hooks fire or if the orchestrator
# manually included the preamble in the task description.
ALREADY_HAS_PREAMBLE=0
if echo "$AGENT_PROMPT" | grep -q "TRUST_REPORT: SCORE="; then
  ALREADY_HAS_PREAMBLE=1
fi

# --- Inject agent-preamble.md (the core quality contract) ---
# This ensures every sub-agent receives the TRUST_REPORT format requirement
# and emits machine-parseable trust scores that feed the quality feedback loop.
PREAMBLE_FILE="$PROJECT_DIR/templates/agent-preamble.md"
if [[ "$ALREADY_HAS_PREAMBLE" -eq 0 ]] && [[ -f "$PREAMBLE_FILE" ]]; then
  PREAMBLE_CONTENT=$(cat "$PREAMBLE_FILE")
  # Interpolate {{phase}} placeholder
  PREAMBLE_CONTENT="${PREAMBLE_CONTENT//\{\{phase\}\}/$PHASE}"
  echo "--- AGENT PREAMBLE (REQUIRED — read before starting) ---"
  echo "$PREAMBLE_CONTENT"
  echo "--- END AGENT PREAMBLE ---"
  echo ""
fi

# --- Output all context ---
echo ""
echo "PROJECT: ${PROJECT_NAME} ($PROJECT_TYPE)"
echo "PHASE: $PHASE"
echo ""
echo "PHASE RULES:"
echo "$RULES"
if [[ -n "$GOTCHAS" ]]; then
  echo ""
  echo "KNOWN TRAPS (auto-detected from your task keywords):"
  echo "$GOTCHAS"
fi
if [[ -n "$ENGRAM_WARNINGS" ]]; then
  echo ""
  echo "RELEVANT DISCOVERIES (from project memory):"
  echo "$ENGRAM_WARNINGS"
fi
if [[ -n "$PROJECT_CONTEXT" ]]; then
  echo ""
  echo -e "PROJECT CONTEXT:$PROJECT_CONTEXT"
fi
if [[ -n "$SQUAD_INFO" ]]; then
  echo ""
  echo "$SQUAD_INFO"
fi

# --- Inject gotchas file if working on COS internals ---
GOTCHAS_FILE="$PROJECT_DIR/templates/project-gotchas.md"
if [[ -n "$AGENT_PROMPT" ]] && [[ -f "$GOTCHAS_FILE" ]]; then
  # Only inject for COS-internal work (mentions lib/, hooks/, packages/, .cognitive-os/)
  if echo "$AGENT_PROMPT" | grep -qiE 'lib/|hooks/|packages/|\.cognitive-os/|settings\.json|cognitive-os\.yaml'; then
    echo ""
    echo "--- PROJECT GOTCHAS (read before modifying COS internals) ---"
    cat "$GOTCHAS_FILE"
  fi
fi

echo ""

exit 0
