"""Audit: docs/08-References/root/adoption-tiers.md must be in sync with its rendered output.

ADR contract: adoption-tiers.md is a derived artifact generated by
scripts/render_adoption_tiers.py from templates/adoption-tiers.md.j2 and
templates/security-profiles/*.json.  Any manual edit to the doc without
re-running the renderer will cause this test to fail.

Run:
    python3 -m pytest tests/audit/test_adoption_tiers_synced.py -v

Lane: audit (parallel-safe — read-only comparison, no shared state mutations).
"""
from __future__ import annotations

import difflib
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
RENDERER = REPO_ROOT / "scripts" / "render_adoption_tiers.py"
COMMITTED_DOC = REPO_ROOT / "docs" / "08-References" / "root" / "adoption-tiers.md"
_GENERATION_NOTICE_PREFIX = "<!-- Generated from"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _strip_generation_notice(text: str) -> str:
    """Remove trailing generation-notice comment and surrounding separators."""
    lines = text.splitlines(keepends=True)
    while lines and lines[-1].strip() in ("", "---"):
        lines.pop()
    if lines and lines[-1].strip().startswith(_GENERATION_NOTICE_PREFIX):
        lines.pop()
    while lines and lines[-1].strip() == "":
        lines.pop()
    return "".join(lines)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.audit
def test_renderer_exists() -> None:
    """scripts/render_adoption_tiers.py must exist and be executable by Python."""
    assert RENDERER.exists(), f"Renderer not found: {RENDERER}"
    assert RENDERER.stat().st_size > 0, "Renderer is empty"


@pytest.mark.audit
def test_adoption_tiers_doc_exists() -> None:
    """docs/08-References/root/adoption-tiers.md must exist."""
    assert COMMITTED_DOC.exists(), f"Doc not found: {COMMITTED_DOC}"


@pytest.mark.audit
def test_adoption_tiers_synced() -> None:
    """Regenerated output must match committed docs/08-References/root/adoption-tiers.md.

    The generation-notice footer (sha + timestamp) is stripped before
    comparison so that the test does not fail on every commit due to a
    different SHA or timestamp.
    """
    with tempfile.NamedTemporaryFile(suffix=".md", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        result = subprocess.run(
            [sys.executable, str(RENDERER), "--output", str(tmp_path)],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=REPO_ROOT,
        )
        assert result.returncode == 0, (
            f"Renderer exited {result.returncode}.\n"
            f"stdout: {result.stdout}\n"
            f"stderr: {result.stderr}"
        )

        regen_text = _strip_generation_notice(tmp_path.read_text(encoding="utf-8"))
        committed_text = _strip_generation_notice(
            COMMITTED_DOC.read_text(encoding="utf-8")
        )

        if regen_text == committed_text:
            return  # pass

        diff = "".join(
            difflib.unified_diff(
                committed_text.splitlines(keepends=True),
                regen_text.splitlines(keepends=True),
                fromfile=str(COMMITTED_DOC.relative_to(REPO_ROOT)),
                tofile="<regenerated>",
            )
        )
        pytest.fail(
            f"docs/08-References/root/adoption-tiers.md is out of sync with rendered output.\n"
            f"Run: python3 scripts/render_adoption_tiers.py\n\n"
            f"Diff (committed → regenerated):\n{diff}"
        )
    finally:
        tmp_path.unlink(missing_ok=True)


@pytest.mark.audit
def test_adoption_tiers_json_flag() -> None:
    """--json flag must emit valid JSON with expected keys."""
    import json

    result = subprocess.run(
        [sys.executable, str(RENDERER), "--json"],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=REPO_ROOT,
    )
    assert result.returncode == 0, f"--json exited {result.returncode}: {result.stderr}"

    data = json.loads(result.stdout)
    assert "tiers" in data, "JSON output missing 'tiers' key"
    assert set(data["tiers"].keys()) == {"lean", "standard", "strict"}

    for tier_key, tier_data in data["tiers"].items():
        assert "hook_count" in tier_data, f"tier {tier_key} missing hook_count"
        assert isinstance(tier_data["hook_count"], int), (
            f"tier {tier_key} hook_count must be int"
        )
        assert tier_data["hook_count"] > 0, (
            f"tier {tier_key} hook_count must be positive"
        )


@pytest.mark.audit
def test_adoption_tiers_hook_counts_match_profiles() -> None:
    """Hook counts in the rendered doc must match the JSON profile files."""
    import json
    import re

    lean_profile = json.loads(
        (REPO_ROOT / "templates" / "security-profiles" / "minimal.json").read_text()
    )
    std_profile = json.loads(
        (REPO_ROOT / "templates" / "security-profiles" / "standard.json").read_text()
    )
    paranoid_profile = json.loads(
        (REPO_ROOT / "templates" / "security-profiles" / "paranoid.json").read_text()
    )

    doc_text = COMMITTED_DOC.read_text(encoding="utf-8")

    # Find "Hooks wired" row in the overview table
    # Pattern: | Hooks wired | ~N (minimal profile) | ~N (standard profile) | ~N (paranoid profile) |
    m = re.search(
        r"\| Hooks wired \| ~(\d+) \([^)]+\) \| ~(\d+) \([^)]+\) \| ~(\d+) \([^)]+\)",
        doc_text,
    )
    assert m is not None, "Could not find 'Hooks wired' row in tier overview table"

    lean_count_in_doc = int(m.group(1))
    std_count_in_doc = int(m.group(2))
    strict_count_in_doc = int(m.group(3))

    assert lean_count_in_doc == lean_profile["_hook_count"], (
        f"Lean hook count in doc ({lean_count_in_doc}) != "
        f"minimal.json._hook_count ({lean_profile['_hook_count']})"
    )
    assert std_count_in_doc == std_profile["_hook_count"], (
        f"Standard hook count in doc ({std_count_in_doc}) != "
        f"standard.json._hook_count ({std_profile['_hook_count']})"
    )
    assert strict_count_in_doc == paranoid_profile["_hook_count"], (
        f"Strict hook count in doc ({strict_count_in_doc}) != "
        f"paranoid.json._hook_count ({paranoid_profile['_hook_count']})"
    )
