#!/usr/bin/env bash
# SCOPE: os-only
# settings-driver-codex.sh — Project cognitive-os.yaml > harness.hooks
# into .codex/hooks.json for the Codex harness.
#
# ADR-064: canonical hook registry lives in cognitive-os.yaml > harness.hooks.
# This driver is the single path that writes .codex/hooks.json.
#
# Codex limitations (v0.126.0-alpha.8):
#   - Only SessionStart, UserPromptSubmit, Stop, PreToolUse:Bash, PostToolUse:Bash
#     are emitted by the harness.
#   - Codex uses different matcher names: "startup" (SessionStart),
#     "prompt" (UserPromptSubmit), "shutdown" (Stop), "bash" (Bash tool).
#   - PreToolUse and PostToolUse fire only for Bash tool calls.
#   - OMITTED events: SubagentStart, PreCompact, non-Bash Pre/PostToolUse.
#   - TeammateIdle, TaskCreated, TaskCompleted require cos-runner (not yet implemented).
#
# DO NOT EDIT .codex/hooks.json directly.
# This file is generated by: scripts/_lib/settings-driver-codex.sh
# from: cognitive-os.yaml > harness.hooks
#
# Usage:
#   bash scripts/_lib/settings-driver-codex.sh [--check]
#   source scripts/_lib/settings-driver-codex.sh && codex_driver_emit
#
# Flags:
#   --check   Dry-run: exit 0 if .codex/hooks.json is in sync, 1 if drift.
#
# Bash 3.x compatible.

set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"

# ── Resolve project root ───────────────────────────────────────────────────────
if [ -z "${PROJECT_DIR:-}" ]; then
  if [ -f "cognitive-os.yaml" ] || [ -d ".codex" ]; then
    PROJECT_DIR="$(pwd)"
  else
    PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
  fi
fi

HOOKS_FILE="$PROJECT_DIR/.codex/hooks.json"

# ── Parse flags ───────────────────────────────────────────────────────────────
CHECK_MODE=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=true ;;
    --harness=*) : ;;  # accepted but ignored (this driver is Codex-only)
    *) ;;
  esac
done

# ── Build a single Codex hook command entry ───────────────────────────────────
_codex_entry() {
  local script="$1"
  # Codex command: set env then conditionally run the script (guard against
  # missing script during first-install when hooks.json is written before
  # self-install.sh has run).
  # NOTE: the JSON "command" string must use escaped double quotes for $PWD paths,
  # matching the format in the original hand-maintained .codex/hooks.json.
  printf '        {\n          "type": "command",\n          "command": "export COGNITIVE_OS_HARNESS=codex; export COGNITIVE_OS_PROJECT_DIR=\\"${COGNITIVE_OS_PROJECT_DIR:-${CODEX_PROJECT_DIR:-$PWD}}\\"; [ -x \\"$PWD/%s\\" ] && bash \\"$PWD/%s\\" || true"\n        }' \
    "$script" "$script"
}

# ── Build a group of Codex hook entries for one event key ────────────────────
# Usage: _codex_group <codex_matcher> <script1> <script2> ...
_codex_group() {
  local matcher="$1"
  shift
  local entries=""
  local first=true
  for script in "$@"; do
    if [ "$first" = true ]; then
      first=false
    else
      entries="$entries,"$'\n'
    fi
    entries="$entries$(_codex_entry "$script")"
  done

  cat <<GROUPEOF
    {
      "hooks": [
$entries
      ],
      "matcher": "$matcher"
    }
GROUPEOF
}

# ── Emit the full .codex/hooks.json content ───────────────────────────────────
codex_driver_emit() {
  python3 - "$PROJECT_DIR" <<'PYEOF'
import json
import sys
from pathlib import Path

import yaml

project_dir = Path(sys.argv[1])
config = yaml.safe_load((project_dir / "cognitive-os.yaml").read_text()) or {}
hooks = (config.get("harness") or {}).get("hooks") or {}

# Codex v0.126.x support matrix (ADR-081): lifecycle hooks are native;
# PreToolUse/PostToolUse are Bash-only; non-Bash tool events and COS extension
# events require other runners and must not be projected into hooks.json.
EVENT_ORDER = ["SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop"]
EVENT_MATCHERS = {
    "SessionStart": "startup",
    "UserPromptSubmit": "prompt",
    "Stop": "shutdown",
}
BASH_ONLY_TOOL_EVENTS = {"PreToolUse", "PostToolUse"}


def codex_matcher(entry: dict) -> str | None:
    event = entry.get("event")
    if event in EVENT_MATCHERS:
        return EVENT_MATCHERS[event]
    if event in BASH_ONLY_TOOL_EVENTS and str(entry.get("matcher") or "") == "Bash":
        return "bash"
    return None


def command_for(script: str) -> dict:
    return {
        "type": "command",
        "command": (
            'export COGNITIVE_OS_HARNESS=codex; '
            'export COGNITIVE_OS_PROJECT_DIR="${COGNITIVE_OS_PROJECT_DIR:-${CODEX_PROJECT_DIR:-$PWD}}"; '
            f'[ -x "$PWD/{script}" ] && bash "$PWD/{script}" || true'
        ),
    }


def groups_for(event: str) -> list[dict]:
    by_matcher: dict[str, list[dict]] = {}
    for entry in hooks.values():
        if not isinstance(entry, dict) or entry.get("event") != event:
            continue
        matcher = codex_matcher(entry)
        if matcher is None:
            continue
        script = entry.get("script")
        if not script:
            continue
        by_matcher.setdefault(matcher, []).append(command_for(str(script)))
    return [{"hooks": entries, "matcher": matcher} for matcher, entries in by_matcher.items()]


output = {event: groups_for(event) for event in EVENT_ORDER}
print(json.dumps(output, indent=2))
PYEOF
}

# ── Main entrypoint (when invoked directly, not sourced) ──────────────────────
if [ "$SCRIPT_SOURCE" = "$0" ]; then
  if [ "$CHECK_MODE" = "true" ]; then
    if [ ! -f "$HOOKS_FILE" ]; then
      echo "DRIFT: $HOOKS_FILE does not exist." >&2
      exit 1
    fi
    TMP_GENERATED="$(mktemp)"
    trap 'rm -f "$TMP_GENERATED"' EXIT
    codex_driver_emit > "$TMP_GENERATED"
    if command -v python3 >/dev/null 2>&1; then
      python3 -c "
import json, sys
with open('$TMP_GENERATED') as f: a = json.dumps(json.load(f), sort_keys=True, indent=2)
with open('$HOOKS_FILE') as f: b = json.dumps(json.load(f), sort_keys=True, indent=2)
if a != b:
    print('DRIFT detected between generated output and $HOOKS_FILE', file=sys.stderr)
    sys.exit(1)
else:
    print('OK: $HOOKS_FILE is in sync with canonical harness.hooks')
"
    else
      if ! diff -q "$TMP_GENERATED" "$HOOKS_FILE" >/dev/null 2>&1; then
        echo "DRIFT: $HOOKS_FILE differs from generated output." >&2
        exit 1
      fi
      echo "OK: $HOOKS_FILE is in sync (byte-level check, python3 not available)"
    fi
    exit 0
  fi

  # Normal mode: write .codex/hooks.json (atomic)
  mkdir -p "$(dirname "$HOOKS_FILE")"
  if [ -f "$HOOKS_FILE" ]; then
    cp "$HOOKS_FILE" "$HOOKS_FILE.bak"
  fi
  TMP_OUT="$(mktemp)"
  trap 'rm -f "$TMP_OUT"' EXIT
  codex_driver_emit > "$TMP_OUT"
  mv "$TMP_OUT" "$HOOKS_FILE"
  hook_count=$(grep -c '"command":' "$HOOKS_FILE" || true)
  echo "settings-driver-codex: wrote $HOOKS_FILE ($hook_count hook commands)"
fi
