#!/usr/bin/env bash
# SCOPE: os-only
# settings-driver-codex.sh — Project cognitive-os.yaml > harness.hooks
# into .codex/hooks.json for the Codex harness.
#
# ADR-064: canonical hook registry lives in cognitive-os.yaml > harness.hooks.
# This driver is the single path that writes .codex/hooks.json.
#
# Codex limitations (v0.126.0-alpha.8):
#   - Only SessionStart, UserPromptSubmit, Stop, PreToolUse:Bash, PostToolUse:Bash
#     are emitted by the harness.
#   - Codex uses different matcher names: "startup" (SessionStart),
#     "prompt" (UserPromptSubmit), "shutdown" (Stop), "bash" (Bash tool).
#   - PreToolUse and PostToolUse fire only for Bash tool calls.
#   - OMITTED events: SubagentStart, PreCompact, non-Bash Pre/PostToolUse.
#   - TeammateIdle, TaskCreated, TaskCompleted require cos-runner (not yet implemented).
#
# DO NOT EDIT .codex/hooks.json directly.
# This file is generated by: scripts/_lib/settings-driver-codex.sh
# from: cognitive-os.yaml > harness.hooks
#
# Usage:
#   bash scripts/_lib/settings-driver-codex.sh [--check]
#   source scripts/_lib/settings-driver-codex.sh && codex_driver_emit
#
# Flags:
#   --check   Dry-run: exit 0 if .codex/hooks.json is in sync, 1 if drift.
#
# Bash 3.x compatible.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Resolve project root ───────────────────────────────────────────────────────
if [ -z "${PROJECT_DIR:-}" ]; then
  if [ -f "cognitive-os.yaml" ] || [ -d ".codex" ]; then
    PROJECT_DIR="$(pwd)"
  else
    PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
  fi
fi

HOOKS_FILE="$PROJECT_DIR/.codex/hooks.json"

# ── Parse flags ───────────────────────────────────────────────────────────────
CHECK_MODE=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=true ;;
    --harness=*) : ;;  # accepted but ignored (this driver is Codex-only)
    *) ;;
  esac
done

# ── Build a single Codex hook command entry ───────────────────────────────────
_codex_entry() {
  local script="$1"
  # Codex command: set env then conditionally run the script (guard against
  # missing script during first-install when hooks.json is written before
  # self-install.sh has run).
  # NOTE: the JSON "command" string must use escaped double quotes for $PWD paths,
  # matching the format in the original hand-maintained .codex/hooks.json.
  printf '        {\n          "type": "command",\n          "command": "export COGNITIVE_OS_HARNESS=codex; export COGNITIVE_OS_PROJECT_DIR=\\"${COGNITIVE_OS_PROJECT_DIR:-${CODEX_PROJECT_DIR:-$PWD}}\\"; [ -x \\"$PWD/%s\\" ] && bash \\"$PWD/%s\\" || true"\n        }' \
    "$script" "$script"
}

# ── Build a group of Codex hook entries for one event key ────────────────────
# Usage: _codex_group <codex_matcher> <script1> <script2> ...
_codex_group() {
  local matcher="$1"
  shift
  local entries=""
  local first=true
  for script in "$@"; do
    if [ "$first" = true ]; then
      first=false
    else
      entries="$entries,"$'\n'
    fi
    entries="$entries$(_codex_entry "$script")"
  done

  cat <<GROUPEOF
    {
      "hooks": [
$entries
      ],
      "matcher": "$matcher"
    }
GROUPEOF
}

# ── Emit the full .codex/hooks.json content ───────────────────────────────────
codex_driver_emit() {
  # Generated by scripts/_lib/settings-driver-codex.sh from cognitive-os.yaml > harness.hooks
  # DO NOT EDIT — re-run the driver to regenerate.
  #
  # OMITTED events (not supported by Codex v0.126.0-alpha.8):
  #   SubagentStart    — not emitted by Codex
  #   PreCompact       — not emitted by Codex
  #   TeammateIdle     — COS extension, requires cos-runner
  #   TaskCreated      — COS extension, requires cos-runner
  #   TaskCompleted    — COS extension, requires cos-runner
  #
  # OMITTED matchers (Bash-only Pre/PostToolUse in Codex):
  #   PreToolUse  Edit|Write, Agent, TodoWrite, Skill, mcp__*, "" (all-tools)
  #   PostToolUse Edit|Write, Agent, TodoWrite, Skill, mcp__*, Bash|Edit|Write, "" (all-tools)
  #
  # SessionStart maps to Codex matcher "startup"
  # UserPromptSubmit maps to Codex matcher "prompt"
  # Stop maps to Codex matcher "shutdown"
  # PreToolUse:Bash maps to Codex matcher "bash"
  # PostToolUse:Bash maps to Codex matcher "bash"

  local session_start
  session_start=$(_codex_group "startup" \
    "hooks/self-install.sh" \
    "hooks/session-init.sh" \
    "hooks/host-tool-doctor.sh" \
    "hooks/profile-drift-autoapply.sh" \
    "hooks/reaper-daemon-launcher.sh" \
    "hooks/session-watchdog-launcher.sh" \
    "hooks/docker-drift-detector.sh" \
    "hooks/cos-executor-daemon-launcher.sh" \
    "hooks/engram-daemon-launcher.sh" \
    "hooks/crash-recovery.sh" \
    "hooks/session-resume.sh" \
    "hooks/infra-health.sh" \
    "hooks/aspirational-audit-weekly.sh" \
    "hooks/self-knowledge-refresh.sh" \
    "hooks/session-start-worktree-nudge.sh" \
    "hooks/session-startup-protocol.sh" \
    "hooks/mcp-scan.sh" \
  )

  local user_prompt_submit
  user_prompt_submit=$(_codex_group "prompt" \
    "hooks/session-heartbeat.sh" \
    "hooks/user-prompt-capture.sh" \
    "hooks/session-wrapup-trigger.sh" \
    "hooks/memory-prefetch.sh" \
  )

  # PreToolUse: Bash only (Codex limitation — Bash is the only supported matcher)
  local pre_bash
  pre_bash=$(_codex_group "bash" \
    "hooks/rate-limit-precheck.sh" \
    "hooks/agent-bash-cwd-enforcer.sh" \
    "hooks/rate-limiter.sh" \
    "hooks/destructive-rm-blocker.sh" \
    "hooks/git-commit-scope-guard.sh" \
  )

  # PostToolUse: Bash only (Codex limitation)
  local post_bash
  post_bash=$(_codex_group "bash" \
    "hooks/error-pipeline.sh" \
    "hooks/result-truncator.sh" \
    "hooks/rate-limit-drain.sh" \
    "hooks/audit-id-enricher.sh" \
  )

  local stop_hooks
  stop_hooks=$(_codex_group "shutdown" \
    "hooks/session-cleanup.sh" \
    "hooks/session-learning.sh" \
    "hooks/git-context-capture.sh" \
    "hooks/session-changelog.sh" \
    "hooks/kpi-trigger.sh" \
    "hooks/engram-crystallize-on-session-end.sh" \
    "hooks/session-summary-reminder.sh" \
  )

  # Assemble the full JSON document
  printf '{\n'
  printf '  "SessionStart": [\n'
  printf '%s\n' "$session_start"
  printf '  ],\n'

  printf '  "UserPromptSubmit": [\n'
  printf '%s\n' "$user_prompt_submit"
  printf '  ],\n'

  printf '  "PreToolUse": [\n'
  printf '%s\n' "$pre_bash"
  printf '  ],\n'

  printf '  "PostToolUse": [\n'
  printf '%s\n' "$post_bash"
  printf '  ],\n'

  printf '  "Stop": [\n'
  printf '%s\n' "$stop_hooks"
  printf '  ]\n'
  printf '}\n'
}

# ── Main entrypoint (when invoked directly, not sourced) ──────────────────────
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  if [ "$CHECK_MODE" = "true" ]; then
    if [ ! -f "$HOOKS_FILE" ]; then
      echo "DRIFT: $HOOKS_FILE does not exist." >&2
      exit 1
    fi
    TMP_GENERATED="$(mktemp)"
    trap 'rm -f "$TMP_GENERATED"' EXIT
    codex_driver_emit > "$TMP_GENERATED"
    if command -v python3 >/dev/null 2>&1; then
      python3 -c "
import json, sys
with open('$TMP_GENERATED') as f: a = json.dumps(json.load(f), sort_keys=True, indent=2)
with open('$HOOKS_FILE') as f: b = json.dumps(json.load(f), sort_keys=True, indent=2)
if a != b:
    print('DRIFT detected between generated output and $HOOKS_FILE', file=sys.stderr)
    sys.exit(1)
else:
    print('OK: $HOOKS_FILE is in sync with canonical harness.hooks')
"
    else
      if ! diff -q "$TMP_GENERATED" "$HOOKS_FILE" >/dev/null 2>&1; then
        echo "DRIFT: $HOOKS_FILE differs from generated output." >&2
        exit 1
      fi
      echo "OK: $HOOKS_FILE is in sync (byte-level check, python3 not available)"
    fi
    exit 0
  fi

  # Normal mode: write .codex/hooks.json (atomic)
  mkdir -p "$(dirname "$HOOKS_FILE")"
  if [ -f "$HOOKS_FILE" ]; then
    cp "$HOOKS_FILE" "$HOOKS_FILE.bak"
  fi
  TMP_OUT="$(mktemp)"
  trap 'rm -f "$TMP_OUT"' EXIT
  codex_driver_emit > "$TMP_OUT"
  mv "$TMP_OUT" "$HOOKS_FILE"
  hook_count=$(grep -c '"command":' "$HOOKS_FILE" || true)
  echo "settings-driver-codex: wrote $HOOKS_FILE ($hook_count hook commands)"
fi
