#!/usr/bin/env bash
# SCOPE: os-only
# settings-driver-bare.sh — Project cognitive-os.yaml > harness.hooks
# into .cognitive-os/cos-runner-hooks.json for the Bare-CLI harness.
#
# ADR-064 Surface 2 Task 2.4: canonical hook registry lives in
# cognitive-os.yaml > harness.hooks. This driver is the single path that
# writes the bare-CLI projection consumed by the BareCliAdapter
# (lib/harness_adapter/bare_cli.py) when cos-agent / cos-skill run outside
# any other harness (CI, headless shell).
#
# Output file: .cognitive-os/cos-runner-hooks.json
# Shape:       cos_runner_event_json (manifests/harness-driver-capabilities.yaml)
#
# Bare-CLI capability matrix (manifests/harness-driver-capabilities.yaml):
#   supported   : SessionStart, UserPromptSubmit, ToolUseStart, ToolUseEnd, SessionEnd
#   unsupported : PreCompact, SubagentStart, TeammateIdle, TaskCreated, TaskCompleted
#
# COS event → bare-cli canonical event mapping:
#   SessionStart      → session_start
#   UserPromptSubmit  → user_prompt_submit
#   PreToolUse        → tool_use_start
#   PostToolUse       → tool_use_end
#   Stop              → session_end
#
# DO NOT EDIT .cognitive-os/cos-runner-hooks.json directly.
# This file is generated by: scripts/_lib/settings-driver-bare.sh
# from: cognitive-os.yaml > harness.hooks
#
# Usage:
#   bash scripts/_lib/settings-driver-bare.sh [--check]
#   source scripts/_lib/settings-driver-bare.sh && bare_driver_emit
#
# Flags:
#   --check          Dry-run: exit 0 if file is in sync, 1 if drift.
#   --harness=*      Accepted but ignored (this driver is bare-cli-only).
#
# Bash 3.x compatible.

set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"
COS_SOURCE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
if [ -z "${PYTHON_BIN:-}" ]; then
  if [ -x "$COS_SOURCE_DIR/.venv/bin/python" ]; then
    PYTHON_BIN="$COS_SOURCE_DIR/.venv/bin/python"
  else
    PYTHON_BIN="python3"
  fi
fi

# ── Resolve project root ───────────────────────────────────────────────────────
if [ -z "${PROJECT_DIR:-}" ]; then
  if [ -f "cognitive-os.yaml" ] || [ -d ".cognitive-os" ]; then
    PROJECT_DIR="$(pwd)"
  else
    PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
  fi
fi

HOOKS_FILE="$PROJECT_DIR/.cognitive-os/cos-runner-hooks.json"

# ── Parse flags ───────────────────────────────────────────────────────────────
CHECK_MODE=false
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_MODE=true ;;
    --harness=*) : ;;  # accepted but ignored (this driver is bare-cli-only)
    *) ;;
  esac
done

# ── Emit the full .cognitive-os/cos-runner-hooks.json content ────────────────
# Strategy: delegate JSON synthesis to python3 + PyYAML so we read the same
# canonical hook registry that drives Codex / Claude Code, with no shell-side
# YAML parsing risk.  See settings-driver-codex.sh for the parallel pattern.
bare_driver_emit() {
  "$PYTHON_BIN" - "$PROJECT_DIR" <<'PYEOF'
import json
import sys
from pathlib import Path

import yaml

project_dir = Path(sys.argv[1])
config = yaml.safe_load((project_dir / "cognitive-os.yaml").read_text()) or {}
hooks = (config.get("harness") or {}).get("hooks") or {}

# Bare-CLI capability matrix (mirror manifests/harness-driver-capabilities.yaml):
# only events with status=supported in the bare_cli driver may project here.
COS_TO_BARE_EVENT = {
    "SessionStart": "session_start",
    "UserPromptSubmit": "user_prompt_submit",
    "PreToolUse": "tool_use_start",
    "PostToolUse": "tool_use_end",
    "Stop": "session_end",
}

# Canonical bare-cli event order (stable output for diffs).
BARE_EVENT_ORDER = [
    "session_start",
    "user_prompt_submit",
    "tool_use_start",
    "tool_use_end",
    "session_end",
]


def hook_entry(name: str, entry: dict) -> dict:
    """Render one hook into the cos-runner-hooks.json shape.

    Bare-CLI consumers (cos-agent / cos-skill) need:
      - script path (relative to project root)
      - matcher (tool pattern; empty string for unmatched events)
      - async hint (fire-and-forget vs blocking)
      - scope tag (preserved for debugging / kill-switch logic)
    """
    return {
        "name": name,
        "script": str(entry.get("script") or ""),
        "matcher": str(entry.get("matcher") or ""),
        "async": bool(entry.get("async", False)),
        "scope": str(entry.get("scope") or ""),
    }


by_event: dict[str, list[dict]] = {ev: [] for ev in BARE_EVENT_ORDER}
for name, entry in hooks.items():
    if not isinstance(entry, dict):
        continue
    cos_event = entry.get("event")
    bare_event = COS_TO_BARE_EVENT.get(str(cos_event) or "")
    if not bare_event:
        # Event is unsupported by bare-cli (PreCompact, SubagentStart,
        # TeammateIdle, TaskCreated, TaskCompleted, etc.).  Drop silently —
        # parity policy treats these as advisory, not required.
        continue
    if not entry.get("script"):
        continue
    by_event[bare_event].append(hook_entry(str(name), entry))

output = {
    "schema_version": 1,
    "harness": "bare_cli",
    "generated_by": "scripts/_lib/settings-driver-bare.sh",
    "source": "cognitive-os.yaml > harness.hooks",
    "events": {ev: by_event[ev] for ev in BARE_EVENT_ORDER},
}
print(json.dumps(output, indent=2, sort_keys=False))
PYEOF
}

# ── Main entrypoint (when invoked directly, not sourced) ──────────────────────
if [ "$SCRIPT_SOURCE" = "$0" ]; then
  if [ "$CHECK_MODE" = "true" ]; then
    if [ ! -f "$HOOKS_FILE" ]; then
      echo "DRIFT: $HOOKS_FILE does not exist." >&2
      exit 1
    fi
    TMP_GENERATED="$(mktemp)"
    trap 'rm -f "$TMP_GENERATED"' EXIT
    bare_driver_emit > "$TMP_GENERATED"
    if [ -x "$PYTHON_BIN" ]; then
      "$PYTHON_BIN" -c "
import json, sys
with open('$TMP_GENERATED') as f: a = json.dumps(json.load(f), sort_keys=True, indent=2)
with open('$HOOKS_FILE') as f: b = json.dumps(json.load(f), sort_keys=True, indent=2)
if a != b:
    print('DRIFT detected between generated output and $HOOKS_FILE', file=sys.stderr)
    sys.exit(1)
else:
    print('OK: $HOOKS_FILE is in sync with canonical harness.hooks')
"
    else
      if ! diff -q "$TMP_GENERATED" "$HOOKS_FILE" >/dev/null 2>&1; then
        echo "DRIFT: $HOOKS_FILE differs from generated output." >&2
        exit 1
      fi
      echo "OK: $HOOKS_FILE is in sync (byte-level check, python unavailable)"
    fi
    exit 0
  fi

  # Normal mode: write .cognitive-os/cos-runner-hooks.json (atomic).
  # Place the temp file on the SAME filesystem as the destination to keep
  # the rename atomic — same rationale as settings-driver-claude-code.sh.
  HOOKS_DIR="$(dirname "$HOOKS_FILE")"
  mkdir -p "$HOOKS_DIR"
  if [ -f "$HOOKS_FILE" ]; then
    cp "$HOOKS_FILE" "$HOOKS_FILE.bak"
  fi
  TMP_OUT="$(mktemp "$HOOKS_DIR/.cos-runner-hooks.json.XXXXXX")"
  trap 'rm -f "$TMP_OUT"' EXIT
  bare_driver_emit > "$TMP_OUT"
  mv "$TMP_OUT" "$HOOKS_FILE"
  hook_count=$(grep -c '"script":' "$HOOKS_FILE" || true)
  echo "settings-driver-bare: wrote $HOOKS_FILE ($hook_count hook entries)"
fi
