#!/usr/bin/env python3
# SCOPE: both
"""
compose-agent-prompt.py — Prepend trap warnings to an agent prompt before launch.

Usage:
    echo "register new hook in settings.json" | python3 scripts/compose-agent-prompt.py
    python3 scripts/compose-agent-prompt.py < draft-prompt.txt
    python3 scripts/compose-agent-prompt.py path/to/draft-prompt.txt

Reads trap definitions from templates/project-gotchas.md relative to the repo root.
Matches keywords against the input prompt; if any match, prepends a
"⚠ PROJECT TRAPS DETECTED:" warning section at the top.

No match → prompt passes through unchanged.
Exit code 0 always (advisory, never blocking).
"""

import re
import sys
import os
from pathlib import Path


# ---------------------------------------------------------------------------
# Trap keyword patterns — derived from templates/project-gotchas.md sections.
# Each entry: (pattern, trap_line)
# Pattern is matched case-insensitively against the full input prompt.
# Trap line is the gotcha text to surface when the pattern fires.
# ---------------------------------------------------------------------------

# Loaded dynamically from the gotchas file; these are fallbacks if the file
# cannot be read.
FALLBACK_TRAPS = [
    (
        r"settings\.json",
        "settings.json is GENERATED by scripts/apply-efficiency-profile.sh. "
        "Never edit directly. Update the script, then run it.",
    ),
    (
        r"lib/[a-zA-Z0-9_]+\.py",
        "lib/*.py are SYMLINKS → packages/*/lib/*.py. Never replace package files. "
        "Verify: ls -la lib/<file>.py",
    ),
    (
        r"packages/",
        "lib/*.py are SYMLINKS → packages/*/lib/*.py. Never replace package files. "
        "Verify symlinks first: ls -la lib/",
    ),
    (
        r"efficiency[\s_-]?profile",
        "settings.json is GENERATED by scripts/apply-efficiency-profile.sh. "
        "Never edit directly. Update the script, then run it.",
    ),
    (
        r"cognitive-os\.yaml",
        "cognitive-os.yaml: read current value first (grep it). "
        "Don't duplicate existing sections.",
    ),
    (
        r"\.cognitive-os/",
        ".cognitive-os/ = OS kernel (universal). .claude/ = driver (Claude Code-specific). "
        "Don't mix.",
    ),
    (
        r"hooks/.*\.sh.*register|register.*hook",
        "hooks/*.sh (new): must add hook to a profile tier via scripts/apply-efficiency-profile.sh. "
        "Never register directly in settings.json.",
    ),
]


def find_repo_root() -> Path:
    """Walk up from this script's location to find the repo root (contains .git)."""
    candidate = Path(__file__).resolve().parent
    for _ in range(8):  # max 8 levels up
        if (candidate / ".git").exists():
            return candidate
        parent = candidate.parent
        if parent == candidate:
            break
        candidate = parent
    # Fallback: assume script lives in <root>/scripts/
    return Path(__file__).resolve().parent.parent


def load_traps_from_gotchas(gotchas_path: Path) -> list[tuple[str, str]]:
    """
    Parse templates/project-gotchas.md and extract (keyword_pattern, trap_text) pairs.

    Strategy:
    - Lines containing a bold term (** ... **) followed by → or : are trap definitions.
    - Table rows (| ... |) where the first cell contains a file path are also traps.
    - We extract the full line as the trap_text and derive a keyword pattern from
      the first bold term or the first cell.
    """
    if not gotchas_path.exists():
        return []

    text = gotchas_path.read_text(encoding="utf-8")
    traps: list[tuple[str, str]] = []
    seen_patterns: set[str] = set()

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith(">"):
            continue

        # Match bold-term trap lines: **something** → or **something**:
        bold_match = re.match(r"\*\*([^*]+)\*\*\s*[→:–-]", stripped)
        if bold_match:
            term = bold_match.group(1).strip()
            # Build a keyword pattern: escape special regex chars, allow flexible spacing
            pattern = re.escape(term).replace(r"\*", r"[*]").replace(r"\ ", r"[\s_/-]?")
            if pattern not in seen_patterns:
                seen_patterns.add(pattern)
                # Use the raw line (stripped of leading dashes/bullets) as trap text
                trap_text = re.sub(r"^[-*•]\s*", "", stripped)
                traps.append((pattern, trap_text))
            continue

        # Match table rows: | `file/path` | ... | explanation |
        if stripped.startswith("|") and "|" in stripped[1:]:
            cells = [c.strip() for c in stripped.split("|") if c.strip()]
            if len(cells) >= 2 and cells[0] not in ("If touching...", "---", "—"):
                raw_keyword = cells[0].strip("`").strip()
                if raw_keyword and not raw_keyword.startswith("-"):
                    # Build pattern from the file path keyword
                    pattern = re.escape(raw_keyword)
                    if pattern not in seen_patterns:
                        seen_patterns.add(pattern)
                        trap_text = " | ".join(cells)
                        traps.append((pattern, trap_text))

    return traps


def match_traps(
    prompt: str, traps: list[tuple[str, str]]
) -> list[str]:
    """Return list of unique trap_text strings whose pattern matches the prompt."""
    matched: list[str] = []
    seen: set[str] = set()
    for pattern, trap_text in traps:
        try:
            if re.search(pattern, prompt, re.IGNORECASE) and trap_text not in seen:
                matched.append(trap_text)
                seen.add(trap_text)
        except re.error:
            # Malformed pattern — skip silently
            pass
    return matched


def build_warning_section(matched_traps: list[str]) -> str:
    """Format the warning block to prepend to the prompt."""
    lines = ["⚠ PROJECT TRAPS DETECTED — read before executing:", ""]
    for trap in matched_traps:
        lines.append(f"  • {trap}")
    lines.append("")
    lines.append(
        "These are known pitfalls for this codebase. "
        "Follow the guidance above before making changes."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def compose(prompt: str, gotchas_path: Path) -> str:
    """Return the prompt, prepending a trap warning if any traps match."""
    traps = load_traps_from_gotchas(gotchas_path)
    if not traps:
        # Fall back to hardcoded list so the script still works if gotchas file moves
        traps = FALLBACK_TRAPS

    matched = match_traps(prompt, traps)
    if not matched:
        return prompt

    warning = build_warning_section(matched)
    return warning + prompt


def main() -> None:
    repo_root = find_repo_root()
    gotchas_path = repo_root / "templates" / "project-gotchas.md"

    # Input: optional positional arg (file path) or stdin
    if len(sys.argv) > 1:
        input_path = Path(sys.argv[1])
        try:
            prompt = input_path.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"Error reading {input_path}: {exc}", file=sys.stderr)
            sys.exit(1)
    else:
        prompt = sys.stdin.read()

    result = compose(prompt, gotchas_path)
    sys.stdout.write(result)
    # Ensure final newline
    if result and not result.endswith("\n"):
        sys.stdout.write("\n")


if __name__ == "__main__":
    main()
