#!/usr/bin/env python3
"""cos-chaos-template — Chaos test skeleton generator for dormant components.

Generates tests/chaos/test_{component_name}_exercised.py with:
  - Fixture for temp environment
  - Trigger invocation (subprocess or direct)
  - Assertion pattern: exit code + JSONL row emitted OR state change observable
  - PLACEHOLDER sections for environment-specific configuration

Usage:
  python3 scripts/cos-chaos-template.py <component-path> [--trigger DESCRIPTION]
  python3 scripts/cos-chaos-template.py hooks/secret-detector.sh
  python3 scripts/cos-chaos-template.py hooks/auto-verify.sh --trigger "Agent PostToolUse with ACCEPTANCE CRITERIA block"
"""
from __future__ import annotations

import argparse
import re
import sys
import textwrap
from pathlib import Path


# ── Template fragments ────────────────────────────────────────────────────────

_HOOK_TEMPLATE = '''\
"""Exercised chaos test for {component_path}.

Tier: {tier}
Trigger: {trigger}

This skeleton was generated by cos-chaos-template.py (ADR-041).
Fill in the PLACEHOLDER sections with environment-specific configuration.

Contract:
  - The component must be invocable without requiring the full Claude Code runtime.
  - Tests must pass in a clean CI environment (no external services unless skipif guarded).
  - Each test appends a row to chaos-runs.jsonl logging the exercise event.
"""
from __future__ import annotations

import json
import os
import subprocess
import time
from pathlib import Path

import pytest

_PROJ_ROOT = Path(__file__).resolve().parent.parent.parent
_COMPONENT = _PROJ_ROOT / "{component_path}"
_CHAOS_RUNS_REL = ".cognitive-os/metrics/chaos-runs.jsonl"


# ── Helpers ───────────────────────────────────────────────────────────────────

def _setup_project(tmp_path: Path) -> None:
    """Create minimal .cognitive-os/ project structure."""
    (tmp_path / ".cognitive-os" / "runtime").mkdir(parents=True)
    (tmp_path / ".cognitive-os" / "metrics").mkdir(parents=True)
    (tmp_path / ".claude").mkdir(parents=True, exist_ok=True)


def _write_chaos_run(tmp_path: Path, component: str, scenario: str, passed: bool) -> None:
    """Append an exercise record to chaos-runs.jsonl."""
    log = tmp_path / _CHAOS_RUNS_REL
    row = {{
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "event_type": "component.exercised",
        "component": component,
        "scenario": scenario,
        "passed": passed,
        "source": "chaos-test",
    }}
    with log.open("a") as fh:
        fh.write(json.dumps(row) + "\\n")


def _run_component(
    component_path: Path,
    tmp_path: Path,
    stdin_payload: str = "",
    env_extra: dict | None = None,
) -> subprocess.CompletedProcess:
    """Invoke the component as a subprocess with optional stdin and env."""
    base_env = {{
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        "HOME": os.environ.get("HOME", str(tmp_path)),
        "PROJECT_DIR": str(tmp_path),
        "CLAUDE_PROJECT_DIR": str(tmp_path),
        "COGNITIVE_OS_PROJECT_DIR": str(tmp_path),
        # Suppress external service connections
        "VALKEY_DISABLED": "1",
        "REDIS_DISABLED": "1",
    }}
    if env_extra:
        base_env.update(env_extra)

    # Detect interpreter from extension / shebang
    suffix = component_path.suffix.lower()
    if suffix == ".py":
        cmd = ["python3", str(component_path)]
    elif suffix in (".sh", ""):
        cmd = ["bash", str(component_path)]
    else:
        cmd = [str(component_path)]

    return subprocess.run(
        cmd,
        input=stdin_payload,
        capture_output=True,
        text=True,
        timeout=15,
        env=base_env,
        cwd=str(tmp_path),
    )


# ── Tests ─────────────────────────────────────────────────────────────────────

@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_exists():
    """Sanity: component must exist on disk."""
    assert _COMPONENT.is_file(), f"Expected file at {{_COMPONENT}}"


@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_invocable_with_empty_input(tmp_path: Path):
    """Component must handle empty/minimal input without crashing (exit 0 or 1).

    Most hooks exit 0 when stdin is empty — they guard with `[ -z "$INPUT" ] && exit 0`.
    This test confirms the empty-input safety net works.
    """
    _setup_project(tmp_path)
    result = _run_component(_COMPONENT, tmp_path, stdin_payload="")

    # PLACEHOLDER: adjust expected exit codes if the component blocks on empty input
    assert result.returncode in (0, 1), (
        f"Expected exit 0 or 1 on empty input, got {{result.returncode}}\\n"
        f"stderr: {{result.stderr[:400]}}"
    )
    _write_chaos_run(tmp_path, "{component_path}", "empty_input", result.returncode in (0, 1))


@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_primary_trigger(tmp_path: Path):
    """Exercise the primary trigger scenario.

    Trigger: {trigger}

    PLACEHOLDER: Replace the synthetic_payload below with a realistic
    trigger input matching the component's expected stdin format.
    """
    _setup_project(tmp_path)

    # PLACEHOLDER: construct the real trigger payload
    # For hooks: JSON matching Claude Code's hook stdin format
    # For scripts: command-line args or stdin data
    synthetic_payload = json.dumps({{
        "tool_name": "Bash",  # PLACEHOLDER: adjust tool_name
        "tool_input": {{"command": "echo triggered"}},  # PLACEHOLDER: realistic command
        "exit_code": "1",  # PLACEHOLDER: set to trigger the hook's main logic
        "tool_response": "Error: something failed",  # PLACEHOLDER
    }})

    # PLACEHOLDER: add any required env vars for this component
    env_extra = {{
        "CLAUDE_AGENT_ID": "chaos-test-agent",  # PLACEHOLDER: may not be needed
    }}

    result = _run_component(_COMPONENT, tmp_path, stdin_payload=synthetic_payload, env_extra=env_extra)

    # PLACEHOLDER: assert the expected behavior
    # Examples:
    #   assert result.returncode == 0  # advisory hooks always exit 0
    #   assert result.returncode == 2  # blocking hooks exit 2
    #   assert "BLOCKED" in result.stderr
    #   assert (tmp_path / ".cognitive-os/metrics/some.jsonl").exists()
    assert result.returncode in (0, 1, 2), (
        f"Unexpected exit code {{result.returncode}}\\n"
        f"stdout: {{result.stdout[:400]}}\\n"
        f"stderr: {{result.stderr[:400]}}"
    )

    _write_chaos_run(tmp_path, "{component_path}", "primary_trigger", True)


@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_writes_chaos_run(tmp_path: Path):
    """After exercise, chaos-runs.jsonl must contain at least one component.exercised row."""
    _setup_project(tmp_path)

    # Exercise the component (empty input — guaranteed to complete without side effects)
    _run_component(_COMPONENT, tmp_path, stdin_payload="")
    _write_chaos_run(tmp_path, "{component_path}", "write_audit", True)

    log = tmp_path / _CHAOS_RUNS_REL
    assert log.exists(), f"chaos-runs.jsonl not found at {{log}}"

    rows = []
    for line in log.read_text().splitlines():
        line = line.strip()
        if line:
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                pass

    exercised = [r for r in rows if r.get("event_type") == "component.exercised"]
    assert len(exercised) >= 1, f"Expected >= 1 component.exercised row, got {{len(exercised)}}"
    assert any(r.get("component") == "{component_path}" for r in exercised), (
        f"No row for component '{component_path}' in chaos-runs.jsonl"
    )
'''

_SCRIPT_TEMPLATE = '''\
"""Exercised chaos test for {component_path}.

Tier: {tier}
Trigger: {trigger}

This skeleton was generated by cos-chaos-template.py (ADR-041).
Fill in the PLACEHOLDER sections with environment-specific configuration.
"""
from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path

import pytest

_PROJ_ROOT = Path(__file__).resolve().parent.parent.parent
_COMPONENT = _PROJ_ROOT / "{component_path}"
_CHAOS_RUNS_REL = ".cognitive-os/metrics/chaos-runs.jsonl"


def _write_chaos_run(tmp_path: Path, component: str, scenario: str, passed: bool) -> None:
    log = tmp_path / _CHAOS_RUNS_REL
    log.parent.mkdir(parents=True, exist_ok=True)
    row = {{
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "event_type": "component.exercised",
        "component": component,
        "scenario": scenario,
        "passed": passed,
        "source": "chaos-test",
    }}
    with log.open("a") as fh:
        fh.write(json.dumps(row) + "\\n")


@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_exists():
    """Sanity: component must exist on disk."""
    assert _COMPONENT.is_file()


@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_runs_with_help_or_summary(tmp_path: Path):
    """Script must handle --help or --summary without crashing.

    PLACEHOLDER: adjust the flag to match the script's actual CLI.
    """
    # PLACEHOLDER: adjust flags to match script's actual interface
    result = subprocess.run(
        [sys.executable, str(_COMPONENT), "--summary"],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=str(_PROJ_ROOT),
    )
    # PLACEHOLDER: assert expected output or exit code
    assert result.returncode in (0, 1, 2), (
        f"Unexpected exit code {{result.returncode}}\\n"
        f"stderr: {{result.stderr[:400]}}"
    )
    _write_chaos_run(tmp_path, "{component_path}", "help_flag", result.returncode in (0, 1, 2))


@pytest.mark.skipif(
    not _COMPONENT.exists(),
    reason=f"Component not found: {{_COMPONENT}}",
)
def test_{safe_name}_writes_chaos_run(tmp_path: Path):
    """chaos-runs.jsonl must receive an exercise record."""
    _write_chaos_run(tmp_path, "{component_path}", "existence_check", True)

    log = tmp_path / _CHAOS_RUNS_REL
    assert log.exists()
    rows = [json.loads(l) for l in log.read_text().splitlines() if l.strip()]
    assert any(r.get("component") == "{component_path}" for r in rows)
'''


# ── Classifier (inline, mirrors cos-classify-coverage.py logic) ───────────────

_TIER_A_RE = re.compile(
    r"/blocker/|credential|secret|killswitch|destructive|disk[_-]?full"
    r"|content[_-]?policy|rate[_-]?limit|auto[_-]?rollback|auto[_-]?refine"
    r"|auto[_-]?verify|guardrail|license[_-]?guard|concurrent[_-]?write"
    r"|release[_-]?guard|global[_-]?verify|error[_-]?pipeline|error[_-]?learning",
    re.IGNORECASE,
)
_TIER_B_RE = re.compile(
    r"monitor|scheduler|daemon|scanner|heartbeat|reaper|executor"
    r"|registry|capture|session[_-]?init|session[_-]?end",
    re.IGNORECASE,
)
_TIER_D_RE = re.compile(r"skills/[^/]+/SKILL\.md$|rules/[^/]+\.md$|templates/", re.IGNORECASE)


def _infer_tier(component_path: str) -> str:
    # Tier D first: SKILL.md / rules / templates must not be promoted by keyword match
    if _TIER_D_RE.search(component_path):
        return "D"
    if _TIER_A_RE.search(component_path):
        return "A"
    if _TIER_B_RE.search(component_path):
        return "B"
    return "C"


def _safe_name(component_path: str) -> str:
    """Convert component path to a valid Python identifier."""
    name = Path(component_path).stem  # e.g. "secret-detector"
    name = re.sub(r"[^a-zA-Z0-9]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name


def _is_script(component_path: str) -> bool:
    """Return True if the component is a Python/shell script (not a hook)."""
    path = component_path.lower()
    return (
        path.startswith("scripts/")
        or path.startswith("lib/")
        or Path(component_path).suffix in (".py",)
        and not path.startswith("hooks/")
    )


def generate_skeleton(
    component_path: str,
    trigger: str | None,
    project_dir: Path,
    output_dir: Path,
) -> Path:
    """Generate a chaos test skeleton and write it to output_dir.

    Returns the path of the written test file.
    """
    tier = _infer_tier(component_path)
    safe = _safe_name(component_path)
    trigger_desc = trigger or f"Standard invocation of {component_path}"

    if _is_script(component_path):
        template = _SCRIPT_TEMPLATE
    else:
        template = _HOOK_TEMPLATE

    content = template.format(
        component_path=component_path,
        tier=tier,
        trigger=trigger_desc,
        safe_name=safe,
    )

    output_path = output_dir / f"test_{safe}_exercised.py"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate chaos test skeleton for a dormant component."
    )
    parser.add_argument("component", help="Component path relative to project root (e.g. hooks/secret-detector.sh).")
    parser.add_argument(
        "--trigger",
        default=None,
        help="Description of the trigger condition (used in test docstring).",
    )
    parser.add_argument(
        "--project-dir",
        default=None,
        help="Project root directory (default: auto-detect git root).",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory for generated test (default: <project-dir>/tests/chaos).",
    )
    args = parser.parse_args()

    # Resolve project directory
    if args.project_dir:
        project_dir = Path(args.project_dir).resolve()
    else:
        cwd = Path.cwd()
        candidate = cwd
        while candidate != candidate.parent:
            if (candidate / ".git").exists():
                project_dir = candidate
                break
            candidate = candidate.parent
        else:
            project_dir = cwd

    output_dir = (
        Path(args.output_dir).resolve()
        if args.output_dir
        else project_dir / "tests" / "chaos"
    )

    out_path = generate_skeleton(args.component, args.trigger, project_dir, output_dir)
    tier = _infer_tier(args.component)
    print(f"Generated Tier {tier} skeleton: {out_path}")


if __name__ == "__main__":
    main()
