#!/usr/bin/env python3
# SCOPE: both
"""Generate a comment-free runtime config view for prompt/preamble budgets.

The canonical config remains cognitive-os.yaml. This artifact is only a compact
LLM/runtime-facing projection of keys that affect token, budget, routing, and
loading behavior. It removes comments and long historical/operator sections so
maintainer profiles do not pay the full config as preamble tax.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / ".cognitive-os" / "generated" / "runtime-config.compact.yaml"

TOP_LEVEL_KEYS = (
    "project",
    "context_budget",
    "models",
    "memory",
    "skills",
    "rules",
    "resources",
    "model_capability",
    "llm_providers",
    "tool_replay_ledger",
)

RESOURCE_KEYS = ("budget", "compute", "tokens")
MODEL_KEYS = ("routing", "providers")
MEMORY_KEYS = ("provider", "sync")


def _pick(mapping: dict[str, Any], keys: tuple[str, ...]) -> dict[str, Any]:
    return {key: mapping[key] for key in keys if key in mapping}


def build_compact_config(source: Path = REPO_ROOT / "cognitive-os.yaml") -> dict[str, Any]:
    """Return the compact runtime-facing subset of cognitive-os.yaml."""
    data = yaml.safe_load(source.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        return {}

    out: dict[str, Any] = _pick(data, TOP_LEVEL_KEYS)
    if isinstance(out.get("resources"), dict):
        out["resources"] = _pick(out["resources"], RESOURCE_KEYS)
    if isinstance(out.get("models"), dict):
        out["models"] = _pick(out["models"], MODEL_KEYS)
    if isinstance(out.get("memory"), dict):
        out["memory"] = _pick(out["memory"], MEMORY_KEYS)
    return out


def write_compact_config(source: Path, output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    content = yaml.safe_dump(build_compact_config(source), sort_keys=False, allow_unicode=True)
    header = "# AUTO-GENERATED by scripts/generate_runtime_compact_config.py — DO NOT EDIT\n"
    output.write_text(header + content, encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=REPO_ROOT / "cognitive-os.yaml")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    output = write_compact_config(args.source, args.output)
    chars = len(output.read_text(encoding="utf-8"))
    print(f"Wrote {output} ({chars} chars, ~{chars // 4} tokens)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
