#!/usr/bin/env bash
# Generate IDE-specific configs from Cognitive OS rules
# Usage:
#   bash scripts/ide-bridge.sh <ide>     # generate config for a specific IDE
#   bash scripts/ide-bridge.sh --list    # list all supported IDEs
#   bash scripts/ide-bridge.sh --help    # show help
#
# Supported IDEs (15):
#   cursor, windsurf, aider, gemini, copilot, copilot-cli, codex,
#   opencode, trae, roo, continue, augment, warp, cline, zed
#
# Note: hooks ONLY work natively with Claude Code. Other IDEs get the RULES layer.
# Tools with full hook support (Gemini CLI, Copilot CLI, Cursor, Windsurf, Kiro)
# may support hooks natively but require manual hook registration.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RULES_DIR="$PROJECT_ROOT/rules"
COMPACT_RULES="$RULES_DIR/RULES-COMPACT.md"

# ── Helpers ───────────────────────────────────────────────────────────

show_help() {
  cat <<'EOF'
IDE Bridge - Generate IDE-specific configs from Cognitive OS rules

Usage:
  bash scripts/ide-bridge.sh <ide>
  bash scripts/ide-bridge.sh --list
  bash scripts/ide-bridge.sh --help

Supported IDEs (15):
  cursor       .cursor/rules/ directory with individual rule files
  windsurf     .windsurfrules single file with concatenated rules
  aider        .aider.conf.yml with conventions reference
  gemini       GEMINI.md symlinked/generated from CLAUDE.md pattern
  copilot      .github/copilot-instructions.md with project rules
  copilot-cli  .agent.md for GitHub Copilot CLI agent mode
  codex        AGENTS.md for OpenAI Codex CLI
  opencode     .opencode/commands/ directory from rules
  trae         .trae.rules file for Trae (ByteDance)
  roo          .roo/rules-code/ directory for Roo Code
  continue     .continue/rules/ directory for Continue.dev
  augment      .augment/rules/ directory for Augment Code
  warp         WARP.md for Warp terminal
  cline        .clinerules file for Cline
  zed          Prints rules for manual Zed settings.json insertion

What gets generated:
  Rules (behavioral contracts) are converted to each IDE's format.
  Hooks, metrics, memory, and SDD automation require native support
  and may need manual configuration in each IDE.

EOF
}

list_ides() {
  cat <<'EOF'
Supported IDEs (15):
  cursor       → .cursor/rules/
  windsurf     → .windsurfrules
  aider        → .aider.conf.yml
  gemini       → GEMINI.md
  copilot      → .github/copilot-instructions.md
  copilot-cli  → .agent.md
  codex        → AGENTS.md
  opencode     → .opencode/commands/
  trae         → .trae.rules
  roo          → .roo/rules-code/
  continue     → .continue/rules/
  augment      → .augment/rules/
  warp         → WARP.md
  cline        → .clinerules
  zed          → stdout (for settings.json)
EOF
}

count_rules() {
  find "$RULES_DIR" -maxdepth 1 -name '*.md' ! -name 'RULES-COMPACT.md' 2>/dev/null | wc -l | tr -d ' '
}

# Copies individual rule files to a target directory (skipping RULES-COMPACT.md)
copy_rules_to_dir() {
  local target="$1"
  mkdir -p "$target"
  local count=0
  for rule in "$RULES_DIR"/*.md; do
    [ -f "$rule" ] || continue
    local basename
    basename=$(basename "$rule")
    if [ "$basename" = "RULES-COMPACT.md" ]; then
      continue
    fi
    cp "$rule" "$target/$basename"
    count=$((count + 1))
  done
  echo "$count"
}

# Concatenates all rules into a single file with separators
concat_rules_to_file() {
  local target="$1"
  local header="$2"

  {
    echo "$header"
    echo ""
    echo "---"
    echo ""
  } > "$target"

  local count=0
  for rule in "$RULES_DIR"/*.md; do
    [ -f "$rule" ] || continue
    local basename
    basename=$(basename "$rule")
    if [ "$basename" = "RULES-COMPACT.md" ]; then
      continue
    fi
    {
      echo ""
      echo "<!-- Source: rules/$basename -->"
      cat "$rule"
      echo ""
      echo "---"
      echo ""
    } >> "$target"
    count=$((count + 1))
  done
  echo "$count"
}

# Generates a compact rules summary for single-file targets
generate_compact_header() {
  cat <<'HEADEREOF'
# Cognitive OS Rules
# Generated by scripts/ide-bridge.sh
# Full documentation: docs/ide-compatibility.md
#
# These rules define behavioral contracts for AI coding agents.
# Hooks, metrics, and memory require Claude Code or compatible IDE.
# See rules/RULES-COMPACT.md for the full compact index.
HEADEREOF
}

# ── Cursor ────────────────────────────────────────────────────────────

generate_cursor() {
  local target="$PROJECT_ROOT/.cursor/rules"
  local count
  count=$(copy_rules_to_dir "$target")
  echo "Cursor: Generated $count rule files in .cursor/rules/"
  echo "Cursor reads these as AI instructions automatically."
  echo "Note: Register hooks manually in Cursor settings for lifecycle automation."
}

# ── Windsurf ──────────────────────────────────────────────────────────

generate_windsurf() {
  local target="$PROJECT_ROOT/.windsurfrules"
  local header="# Cognitive OS Rules for Windsurf
# Generated by scripts/ide-bridge.sh
# Note: Configure Cascade Hooks manually for lifecycle automation."
  local count
  count=$(concat_rules_to_file "$target" "$header")
  local size
  size=$(wc -c < "$target" | tr -d ' ')
  echo "Windsurf: Generated .windsurfrules with $count rules (${size} bytes)"
  echo "Warning: This is a large single file. Windsurf loads it entirely into context."
}

# ── Aider ─────────────────────────────────────────────────────────────

generate_aider() {
  local target="$PROJECT_ROOT/.aider.conf.yml"
  cat > "$target" << 'AIDEREOF'
# Cognitive OS conventions for Aider
# Generated by scripts/ide-bridge.sh

# Read the compact rules as conventions
read:
  - rules/RULES-COMPACT.md

# Aider configuration
auto-commits: false
lint-cmd: ""

# Convention notes for the AI:
# - Follow the phase-aware behavior in cognitive-os.yaml (project.phase)
# - License policy: BLOCK AGPL, SSPL, BSL. ALLOW MIT, BSD, Apache 2.0, ISC.
# - Every task needs measurable acceptance criteria before starting
# - Classify task complexity (trivial/small/medium/large/critical) before work
# - Admit uncertainties -- "100% confident" is a red flag
# - Never hardcode credentials; use environment variables
# - Check rules/RULES-COMPACT.md for the full behavioral contract
AIDEREOF
  echo "Aider: Generated .aider.conf.yml"
  echo "Aider will read rules/RULES-COMPACT.md as conventions."
}

# ── Gemini CLI ────────────────────────────────────────────────────────

generate_gemini() {
  local target="$PROJECT_ROOT/GEMINI.md"
  if [ -f "$PROJECT_ROOT/CLAUDE.md" ]; then
    cp "$PROJECT_ROOT/CLAUDE.md" "$target"
    echo "Gemini: Generated GEMINI.md (copied from CLAUDE.md)"
  elif [ -f "$COMPACT_RULES" ]; then
    {
      generate_compact_header
      echo ""
      cat "$COMPACT_RULES"
    } > "$target"
    echo "Gemini: Generated GEMINI.md from RULES-COMPACT.md"
  else
    echo "Error: No CLAUDE.md or RULES-COMPACT.md found to generate GEMINI.md" >&2
    exit 1
  fi
  echo "Gemini CLI reads GEMINI.md as global instructions."
}

# ── GitHub Copilot (VS Code) ─────────────────────────────────────────

generate_copilot() {
  local target_dir="$PROJECT_ROOT/.github"
  local target="$target_dir/copilot-instructions.md"
  mkdir -p "$target_dir"
  {
    echo "# Cognitive OS Rules for GitHub Copilot"
    echo "# Generated by scripts/ide-bridge.sh"
    echo ""
    if [ -f "$COMPACT_RULES" ]; then
      cat "$COMPACT_RULES"
    fi
  } > "$target"
  echo "Copilot: Generated .github/copilot-instructions.md"
  echo "GitHub Copilot (VS Code) reads this as project-level instructions."
}

# ── GitHub Copilot CLI ────────────────────────────────────────────────

generate_copilot_cli() {
  local target="$PROJECT_ROOT/.agent.md"
  {
    echo "# Cognitive OS Rules for GitHub Copilot CLI"
    echo "# Generated by scripts/ide-bridge.sh"
    echo ""
    if [ -f "$COMPACT_RULES" ]; then
      cat "$COMPACT_RULES"
    fi
  } > "$target"
  echo "Copilot CLI: Generated .agent.md"
  echo "GitHub Copilot CLI reads .agent.md as agent instructions."
}

# ── OpenAI Codex CLI ──────────────────────────────────────────────────

generate_codex() {
  local target="$PROJECT_ROOT/AGENTS.md"
  {
    echo "# Cognitive OS Rules for OpenAI Codex CLI"
    echo "# Generated by scripts/ide-bridge.sh"
    echo ""
    if [ -f "$COMPACT_RULES" ]; then
      cat "$COMPACT_RULES"
    fi
  } > "$target"
  echo "Codex: Generated AGENTS.md"
  echo "OpenAI Codex CLI reads AGENTS.md as agent instructions."
}

# ── OpenCode ──────────────────────────────────────────────────────────

generate_opencode() {
  local target="$PROJECT_ROOT/.opencode/commands"
  local count
  count=$(copy_rules_to_dir "$target")
  echo "OpenCode: Generated $count rule files in .opencode/commands/"
  echo "OpenCode reads these as command definitions."
}

# ── Trae (ByteDance) ─────────────────────────────────────────────────

generate_trae() {
  local target="$PROJECT_ROOT/.trae.rules"
  local header="# Cognitive OS Rules for Trae
# Generated by scripts/ide-bridge.sh"
  local count
  count=$(concat_rules_to_file "$target" "$header")
  echo "Trae: Generated .trae.rules with $count rules"
  echo "Trae reads .trae.rules as AI instructions."
}

# ── Roo Code ──────────────────────────────────────────────────────────

generate_roo() {
  local target="$PROJECT_ROOT/.roo/rules-code"
  local count
  count=$(copy_rules_to_dir "$target")
  echo "Roo Code: Generated $count rule files in .roo/rules-code/"
  echo "Roo Code reads these as mode-specific rules."
  echo "Tip: Copy to .roo/rules-architect/ and .roo/rules-review/ for other modes."
}

# ── Continue.dev ──────────────────────────────────────────────────────

generate_continue() {
  local target="$PROJECT_ROOT/.continue/rules"
  local count
  count=$(copy_rules_to_dir "$target")
  echo "Continue.dev: Generated $count rule files in .continue/rules/"
  echo "Continue.dev reads these as contextual rules."
}

# ── Augment Code ──────────────────────────────────────────────────────

generate_augment() {
  local target="$PROJECT_ROOT/.augment/rules"
  local count
  count=$(copy_rules_to_dir "$target")
  echo "Augment Code: Generated $count rule files in .augment/rules/"
  echo "Augment reads these as project-level rules."
}

# ── Warp ──────────────────────────────────────────────────────────────

generate_warp() {
  local target="$PROJECT_ROOT/WARP.md"
  if [ -f "$PROJECT_ROOT/CLAUDE.md" ]; then
    cp "$PROJECT_ROOT/CLAUDE.md" "$target"
    echo "Warp: Generated WARP.md (copied from CLAUDE.md)"
  elif [ -f "$COMPACT_RULES" ]; then
    {
      generate_compact_header
      echo ""
      cat "$COMPACT_RULES"
    } > "$target"
    echo "Warp: Generated WARP.md from RULES-COMPACT.md"
  else
    echo "Error: No CLAUDE.md or RULES-COMPACT.md found to generate WARP.md" >&2
    exit 1
  fi
  echo "Warp reads WARP.md as terminal instructions (CLAUDE.md compatible)."
}

# ── Cline ─────────────────────────────────────────────────────────────

generate_cline() {
  local target="$PROJECT_ROOT/.clinerules"
  local header="# Cognitive OS Rules for Cline
# Generated by scripts/ide-bridge.sh"
  local count
  count=$(concat_rules_to_file "$target" "$header")
  echo "Cline: Generated .clinerules with $count rules"
  echo "Cline reads .clinerules as AI instructions."
}

# ── Zed AI ────────────────────────────────────────────────────────────

generate_zed() {
  echo "Zed AI: Rules must be added to Zed's settings.json manually."
  echo ""
  echo "Add the following to your Zed settings.json under 'assistant.default_model.provider':"
  echo ""
  echo "Alternatively, Zed reads .rules files. Generating compact rules file:"
  local target="$PROJECT_ROOT/.zed-rules.md"
  {
    echo "# Cognitive OS Rules for Zed AI"
    echo "# Generated by scripts/ide-bridge.sh"
    echo "# Add relevant sections to your Zed settings.json"
    echo ""
    if [ -f "$COMPACT_RULES" ]; then
      cat "$COMPACT_RULES"
    fi
  } > "$target"
  echo "Zed: Generated .zed-rules.md -- copy relevant sections to Zed settings."
}

# ── Main ──────────────────────────────────────────────────────────────

if [ ! -d "$RULES_DIR" ]; then
  echo "Error: Rules directory not found at $RULES_DIR" >&2
  echo "Are you running this from the Cognitive OS project root?" >&2
  exit 1
fi

case "${1:---help}" in
  cursor)      generate_cursor ;;
  windsurf)    generate_windsurf ;;
  aider)       generate_aider ;;
  gemini)      generate_gemini ;;
  copilot)     generate_copilot ;;
  copilot-cli) generate_copilot_cli ;;
  codex)       generate_codex ;;
  opencode)    generate_opencode ;;
  trae)        generate_trae ;;
  roo)         generate_roo ;;
  continue)    generate_continue ;;
  augment)     generate_augment ;;
  warp)        generate_warp ;;
  cline)       generate_cline ;;
  zed)         generate_zed ;;
  --list)      list_ides ;;
  --help|-h|help) show_help ;;
  *)
    echo "Error: Unknown IDE '$1'" >&2
    echo "Run 'bash scripts/ide-bridge.sh --list' for supported IDEs." >&2
    exit 1
    ;;
esac
