"""Behavior tests for skills batch 2: structural, content, and catalog validation.

Migrated from test-skills-batch2.sh.
Tests 21 skills including the auto-generated directory special case.
"""

import re
import subprocess
from pathlib import Path

import pytest

pytestmark = pytest.mark.behavior

SKILLS_BATCH2 = [
    "plan-feature",
    "readiness-check",
    "recommend-library",
    "repair-status",
    "resource-governor",
    "resume-tasks",
    "retrospective",
    "sandbox-sample",
    "sdd-continue",
    "secret-audit",
    "session-manager",
    "squad-manager",
    "sre-agent",
    "systematic-debugging",
    "test-driven-development",
    "tool-discovery",
    "trust-audit",
    "validate-config",
    "verification-before-completion",
    "memu-context",
    "paperclip-dashboard",
    "auto-generated",
]

EXPERIMENTAL_SKILLS = {"sandbox-sample", "memu-context", "paperclip-dashboard"}

DESCRIPTIVE_SECTION_RE = re.compile(
    r"^## (Purpose|What to Do|What To Do|Overview|When to Use|Goal|Objective|"
    r"What This Skill Does|Description|How It Works|Invocation|Instructions|"
    r"Steps|Procedure|Workflow|Usage|Invoke|Protocol|Trigger|Configuration|"
    r"Execution Protocol|What Gets Validated|Supported Registries|Subcommands)",
    re.MULTILINE,
)


# ---------------------------------------------------------------------------
# Structural tests
# ---------------------------------------------------------------------------


class TestSkillStructureBatch2:

    @pytest.mark.parametrize("skill", SKILLS_BATCH2)
    def test_skill_md_exists(self, skill: str, skills_dir: Path):
        skill_dir = skills_dir / skill
        skill_file = skill_dir / "SKILL.md"
        if skill == "auto-generated":
            # auto-generated might be empty placeholder
            if not skill_file.exists():
                pytest.skip("auto-generated is a placeholder directory")
            return
        assert skill_file.exists(), f"SKILL.md missing for {skill}"

    @pytest.mark.parametrize("skill", [s for s in SKILLS_BATCH2 if s != "auto-generated"])
    def test_has_frontmatter_or_header(self, skill: str, skills_dir: Path):
        skill_file = skills_dir / skill / "SKILL.md"
        if not skill_file.exists():
            pytest.skip(f"SKILL.md missing for {skill}")
        content = skill_file.read_text()
        lines = content.splitlines()
        if not lines:
            pytest.fail(f"Empty SKILL.md for {skill}")
        first_line = lines[0].strip()
        assert first_line.startswith("---") or first_line.startswith("# "), (
            f"missing frontmatter or header for {skill}"
        )

    @pytest.mark.parametrize("skill", [s for s in SKILLS_BATCH2 if s != "auto-generated"])
    def test_has_content_sections(self, skill: str, skills_dir: Path):
        skill_file = skills_dir / skill / "SKILL.md"
        if not skill_file.exists():
            pytest.skip(f"SKILL.md missing for {skill}")
        content = skill_file.read_text()
        assert re.search(r"^## ", content, re.MULTILINE), f"no content sections for {skill}"


# ---------------------------------------------------------------------------
# Content tests
# ---------------------------------------------------------------------------


class TestSkillContentBatch2:

    @pytest.mark.parametrize("skill", [s for s in SKILLS_BATCH2 if s != "auto-generated"])
    def test_has_descriptive_section(self, skill: str, skills_dir: Path):
        skill_file = skills_dir / skill / "SKILL.md"
        if not skill_file.exists():
            pytest.skip(f"SKILL.md missing for {skill}")
        content = skill_file.read_text()
        assert DESCRIPTIVE_SECTION_RE.search(content), (
            f"missing descriptive section heading for {skill}"
        )


# ---------------------------------------------------------------------------
# Catalog tests
# ---------------------------------------------------------------------------


class TestSkillCatalogBatch2:

    @pytest.mark.parametrize(
        "skill",
        [s for s in SKILLS_BATCH2 if s != "auto-generated"],
    )
    def test_in_catalog(self, skill: str, skills_dir: Path):
        catalog = skills_dir / "CATALOG.md"
        if not catalog.exists():
            pytest.fail("CATALOG.md not found")
        content = catalog.read_text()
        if skill not in content:
            if skill in EXPERIMENTAL_SKILLS:
                pytest.xfail(f"{skill} not in CATALOG.md (experimental/project-specific skill)")
            else:
                pytest.fail(f"{skill} not in CATALOG.md")


# ---------------------------------------------------------------------------
# auto-generated directory special test
# ---------------------------------------------------------------------------


class TestAutoGeneratedDirectory:

    def test_directory_exists(self, skills_dir: Path):
        auto_dir = skills_dir / "auto-generated"
        assert auto_dir.is_dir(), "auto-generated directory does not exist"

    def test_placeholder_info(self, skills_dir: Path):
        """Informational: checks if auto-generated has any SKILL.md files."""
        auto_dir = skills_dir / "auto-generated"
        if not auto_dir.exists():
            pytest.skip("auto-generated directory missing")
        skill_files = list(auto_dir.rglob("SKILL.md"))
        if len(skill_files) == 0:
            pass  # Informational: placeholder directory
