from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = PROJECT_ROOT / "scripts" / "test-run-inventory.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("test_run_inventory", SCRIPT)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write_run(tmp_path: Path, junit: str, output: str = "") -> Path:
    run_dir = tmp_path / "run"
    run_dir.mkdir()
    (run_dir / "junit.xml").write_text(junit)
    (run_dir / "full-output.txt").write_text(output)
    (run_dir / "exit-code.txt").write_text("1\n")
    (run_dir / "metadata.txt").write_text(
        "timestamp_utc=20260424T000000Z\n"
        "git_branch=main\n"
        "git_commit=abc123\n"
        "args=tests/ -q -ra\n"
    )
    return run_dir


def test_inventory_lists_failures_skips_xfails_and_heuristics(tmp_path: Path) -> None:
    mod = _load_module()
    run_dir = _write_run(
        tmp_path,
        """<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite tests="5" failures="1" errors="1" skipped="2">
    <testcase classname="tests.unit.test_config_drift" name="test_settings_freshness_drift" time="0.1">
      <failure message="settings freshness drift">AssertionError</failure>
    </testcase>
    <testcase classname="tests.integration.test_optional_service" name="test_opik_backend_alive" time="1.2">
      <skipped message="Docker daemon not running" />
    </testcase>
    <testcase classname="tests.unit.test_future_feature" name="test_watchdog_future_path" time="0.3">
      <skipped message="xfail: watchdog not implemented yet" />
    </testcase>
    <testcase classname="tests.contracts.test_projection" name="test_canonical_projection" time="0.5">
      <error message="TimeoutError: Test exceeded 30-second timeout">trace</error>
    </testcase>
    <testcase classname="tests.audit.test_catalog" name="test_catalog_heading_exists" time="0.01" />
  </testsuite>
</testsuites>
""",
    )

    inventory = mod.build_inventory(run_dir)

    assert inventory["counts"] == {
        "error": 1,
        "failed": 1,
        "passed": 1,
        "skipped": 1,
        "xfailed": 1,
    }
    assert inventory["heuristic_tag_counts"]["drift"] >= 1
    assert inventory["heuristic_tag_counts"]["optional-lane"] >= 1
    assert inventory["heuristic_tag_counts"]["aspirational"] >= 1
    assert inventory["heuristic_tag_counts"]["timeout"] >= 1
    assert inventory["heuristic_tag_counts"]["false-positive-risk"] >= 1


def test_write_inventory_creates_markdown_and_json(tmp_path: Path) -> None:
    mod = _load_module()
    run_dir = _write_run(
        tmp_path,
        """<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite tests="1" failures="0" errors="0" skipped="1">
    <testcase classname="tests.audit.test_skills_contracts" name="test_scaffold_output_path" time="0.02">
      <skipped message="output path generated by the skill, not project artifacts" />
    </testcase>
  </testsuite>
</testsuites>
""",
    )

    md_path, json_path = mod.write_inventory(run_dir)

    assert md_path.is_file()
    assert json_path.is_file()
    payload = json.loads(json_path.read_text())
    assert payload["counts"]["skipped"] == 1
    markdown = md_path.read_text()
    assert "Test Run Inventory" in markdown
    assert "Repair Queue" in markdown
    assert "test_scaffold_output_path" in markdown


def test_nodeids_preserve_pytest_class_segments(tmp_path: Path) -> None:
    mod = _load_module()
    run_dir = _write_run(
        tmp_path,
        """<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite tests="1" failures="0" errors="0" skipped="0">
    <testcase classname="tests.unit.test_catalog_loading.TestGenerator" name="test_generator_script_runs" time="0.01" />
  </testsuite>
</testsuites>
""",
    )

    inventory = mod.build_inventory(run_dir)
    item = inventory["items"][0]
    assert item["file"] == "tests/unit/test_catalog_loading.py"
    assert item["nodeid"] == (
        "tests/unit/test_catalog_loading.py::"
        "TestGenerator::test_generator_script_runs"
    )
